### PR TITLE
[cli] Lock semver to fix install command

### PR DESCRIPTION
**Pull request by Brianzchen**
Fixes https://github.com/flow-typed/flow-typed/issues/3988

After deep digging the issue is actually related to the semver package. Versions `7.3.3` and `7.3.4` which are currently latest both break our tests in the following screenshot. We use loose `^` but have a lock file which only tests against current lock which is version `7.3.2`. I've now locked the version but I think we should consider removing the lock file completely as this is a published package and we cannot guarantee the version that will be installed on a users machine matches what's in our yarn.lock (would appreciate feedback on this matter). 

Screen Shot 2021-02-10 at 5 59 42 pm

- Links to documentation: N/A
- Link to GitHub or NPM: N/A
- Type of contribution: fix

Other notes: @GAntoine please make sure this is merged before you do release, it's one of the biggest blockers for new people installing flow-typed

### CODE REVIEW

**Review by AndrewSouthpaw — APPROVED** [review]
Seems reasonable to me. I don't have input on the "should we remove the package lock file", but I haven't done a lot of research into patterns of published packages. I would *imagine* it makes sense to keep the lock file because it helps ensure this package works correctly when installed on someone's machine, but maybe I'm not understanding it correctly.

@Brianzchen if you want you could open a separate issue to drive the discussion. I'll call it out of scope for this PR and merge in your improvement.

**Comment by AndrewSouthpaw** [comment]
cc @GAntoine to do a release after this builds.

**Comment by josemigallas** [comment]
Is there an estimate on when this will be released?

**Comment by Brianzchen** [comment]
@josemigallas Just been released, check `v3.3.0`

**Pull request merged**
