### PR TITLE
[jest] Add mock functions for v22

### PR DESCRIPTION
**Pull request by julienw**
Add mockResolvedValue, mockResolvedValueOnce, mockRejectedValue, mockRejectedValueOnce to jest mocked functions

### CODE REVIEW

**Comment by julienw** [comment]
There are test errors:
```
 * jest_v22.x.x/flow_v0.39.x- (flow-v0.66.0): Unexpected Flow errors(0):
   Warning ------------------------------------------------------------------------------------ 0-test_jest-v22.x.x.js:52:1
   
   Unused suppression comment.
   
      52| // $ExpectError Mock function expected to return Promise<number>, not Promise<string>.
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   
   
   Warning ------------------------------------------------------------------------------------ 0-test_jest-v22.x.x.js:54:1
   
   Unused suppression comment.
   
      54| // $ExpectError Can't return a Promise from a non async function
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   
   
   Warning ------------------------------------------------------------------------------------ 0-test_jest-v22.x.x.js:58:1
   
   Unused suppression comment.
   
      58| // $ExpectError Mock function expected to return Promise<number>, not Promise<string>.
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   
   
   Warning ------------------------------------------------------------------------------------ 0-test_jest-v22.x.x.js:60:1
   
   Unused suppression comment.
   
      60| // $ExpectError Can't return a Promise from a non async function
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
But I don't have a good idea to fix them... Any idea ?

**Comment by villesau** [comment]
Test suite seems to take diff for grandparent instead of parent: https://github.com/flowtype/flow-typed/pull/1920

**Comment by AndrewSouthpaw** [comment]
Restarting build...

**Comment by AndrewSouthpaw** [comment]
Derp. That won't fix the problem. @julienw can you rebase against the latest master? There's a commit that should fix your build problem, assuming @villesau is correct.

**Comment by villesau** [comment]
Oh, sorry i totally misread the errors. They seems to come from Jest, not from unrelated libdefs. So rebasing in this case doesn't help.

**Comment by julienw** [comment]
Yep totally, the error definitely comes from my typing :-) I don't understand why the typing doesn't yield these errors and were seeking for some help.

**Comment by GAntoine** [comment]
@julienw Could you still try rebasing this PR on the latest version of master?

**Comment by julienw** [comment]
Oh sure, I just did !

**Comment by GAntoine** [comment]
Awesome. I just wanted to make sure that the errors were indeed coming from the typings, and that any changes weren't going to fail because of an unrelated issue.

**Comment by AndrewSouthpaw** [comment]
Ping @GAntoine  :) Looks like you had something in mind to check, so I'll let you be the one to pull the trigger on the PR.

**Comment by GAntoine** [comment]
@julienw It seems the specs are failing again, and I don't think it's due to any issues in the master branch. When you get a chance, could you take a look at them?

**Comment by julienw** [comment]
Yes, actually, that's what I said in https://github.com/flowtype/flow-typed/pull/1918#issuecomment-370839427 :) I don't know how to fix these problems and I'd like some help here.
Basically, Flow doesn't report errors here while it should. I use an utility called `ExtractPromiseValue` to try to extract the type of a promise value, but I think I'm not doing it properly...

**Comment by julienw** [comment]
[From my test](https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAAqIPYFsCWAzhAGrIA2ArhAGKUB2qUAvFADxlUQB8AFFniIQOFatwCULblE7UA3AChQkWAhToBBYrOGahO6awAkAYQrk2CqKqRpMOLaVG0GqADRWoe7c4XdF1tYKqOTIhIReyCi4EEj4AF4QACYmoeFsACrSAN6eUMDIANZOXLwAbhQAXFAZktkAvnkFxd4l1OVVNur2gj5cmRJQDQqNgVDB2PSEwFBgUcgxcYlJOgCM1Rjzi4gJyalhhGz0lLgARhCIhlD0EADukdGxO8v74bziAYEKc49LyWsAOmabQgvFWH2+WyeuxWzlWQKKEFaOjBELGEymMx+C2hyx0ACYNlC-ik0odWkcTudLlcbvdNr9nnsye9FNjtjCCQjiijWgDEBBCNhyGVQeCIezcf9nPjuUiHPpnKi2cSmbCuLLgcilQAiABm2GwOrRY3GQA) the `ExtractPromiseValue` util should work. I'll give it another shot.

**Comment by julienw** [comment]
[I simplified the problem in try](https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAAqIPYFsCWAzhAGrIA2ArhAGKUB2qUAvFADxlUQB8AFFniIQOFatwCULblE7UA3AChQkWAhToBBYrOGahO6awAkAYQrk2CqKqRpMOLaVG0GqADRWoe7c4XdFSuDQAFIQhMAAstioANY09GwAKgCCiADmlLgQ9MCEAFxQRgBKEMgAJgDy9OQgqSggbABU3G5QiSXAlIj0hlAA3p68AHQjyOn5bakZWTmE4gXtEJ3dHtYA9I2NnlCNUAAiEGCIEKjIwBBlBZTEUABWYcBDAGb0vLySzNIAbs6S+PThUplbaNNaeXDRGIdLr0HS8H5cBbQ7rzKChcJRWLxJJTTLZXKtRbLHqrKAbLbWHZQADKlDSYygT2wiCg2GqICgx2J-zSUGQUAR1FZjGg-0I+DK0BA2C6UAhsRBYOs8qhSxhOiqqAg8OcSLVKIK6MikOxKXSeNmhORJIUnnJIJpdIZT1cwHwbMIjOZnP19B5fJ9hGw5C+Fy8DiEUF4RoFACZY0NYwBqcSK8GQkpBkMXOHbAW6mzqeyCHxcJLW7ieVFGzFxBJm6b4whW30tW3KjNhYOhsoakW8POCiAFeC2DQR0vUcutquGh61024mYEtoVjx2zYO2n0lkuxhuj1ellcmH+-nHe7oMPeaDRh5xhPJ1OU0Hp2IlS-nXvOHWIvn0EBq3nE16yXJsW2JNsO3fCBPxzZxNW1IcCmQACgIxECcXNZdm1XGcAF9FEpSlAhUI0KgAI0-RIghYfoNwpaxdmtT1+XoCAAHdWgYa4wxVRlXXdeghjTawXiwxtZgKYogSqGo6mQBpmggmE+HQ40sVA7DwLwyCPEI21JVQcgxmgH4WXucI53CSjqKCAJlGgGhsGwOi+gAH08MpsGpTonieApwkQf1PigehMgoiBEFJbzkkIEBGF8yh-IKL5sAlKRwxLYRwtwSLEErdyDNQD1gC9bACmc1zWAGaxvKS-zeCCwKkB5VFcvy+jiJPbooAAViIqB8Ji7A4oS1AGqed4ChvNgOqi6RaspHr6CyxwhmOLNQ14PrxEG-CFAM4jrAUJlsCGWL4sSvynjoyzHhed4hhVTNu3grheAARgABj206XIu0aromm67oeZ5XnEZ7O2JOEbw2rtsy+36-uOqAFDWNZCngSB0BgRAcBZWsBP3ISoAgOBca-KBgFcla1qEOaIoW1p6GwMrZqCnluBEs7AbG67ktu1h7ohp6XsRns4QAIh+6W-sx7HKZOYB8cJqAzHoAByMr6f5G9GQcAM2dW5BgZJ9AhP+876tBkXwceqGJa297qGRv7rf54HJrB8IxadzsXe-LhEPdxQ+cu8afftv3HehmDYYQ-t4c2t73dR46MaxowcZVtXvWJvdLbZcnlavMoabp30GeIJm8pZsL2Zr4QufoNIec9yPBf832Hsh+PVSDvstV4WXvvlxRFZzsvVYJ71NZ1n1iQDA2niNtiS7N8aLYPehO58u27gd-vnbe4PqFDn6-qAA). Maybe the problem is how Flow infers the parameters to `JestMockFn`.

**Comment by AndrewSouthpaw** [comment]
Looks like the errors are different at least. :)

**Comment by julienw** [comment]
Yeah, if you can help to find what doesn't work in the try I mentioned above, it would help a lot. We should have errors in that try but we don't have any. I think the problem is how `JestMockFn` is infered. But maybe this shouldn't be done like this...

**Comment by julienw** [comment]
Otherwise I can just remove these test cases so that we can land this already.

**Comment by AndrewSouthpaw** [comment]
Have you tested this in the wild? Does it work there?

Otherwise I'd change the type def to not extract the promise value and worry about that, just provide something like `Promise<*>`.

**Comment by julienw** [comment]
I think we can't do this. We really want to extract the type because that's what we pass to these functions.

Eg if a mock function returns a `Promise<number>`, we want `mockResolvedValue` to take a `number`. But I can't make flow check it properly.
Same, if a mock function returns a `number` we want that Flow forbids to call `mockResolvedValue`. Again I can't make flow check this.

For example if we were in the Rust world, I could do something like `impl AsyncMock for JestMockFn<A, Promise<R>>` :-)

Maybe we can do something similar here, converting JestMockFn to a class or an interface.


I use this in the wild.

**Comment by julienw** [comment]
> Maybe we can do something similar here, converting JestMockFn to a class or an interface.

I tried it and stumbled on https://github.com/facebook/flow/issues/5437

**Comment by AndrewSouthpaw** [comment]
Hm. Seems like we've been spinning our wheels here for a while. I'd be fine with flipping the table and just putting `any` there. Flow is far from perfect, and we shouldn't let perfect become the enemy of better.

**Comment by julienw** [comment]
I see https://github.com/flow-typed/flow-typed/pull/2396 reused part of this PR to land the feature. I'm a bit surprised that it didn't use `ExtractPromiseType` though. And I find issues on my end for mockRejectedValue, I'm surprised the tests were passing at all...

**Comment by julienw** [comment]
OK I find that the typings are failing for things like:
```js
foo.doAsyncStuff = jest
  .fn()
  .mockResolvedValueOnce(10)
  .mockResolvedValueOnce(42);

foo.doAsyncStuff = jest.fn();
foo.doAsyncStuff.mockRejectedValueOnce(new Error("hello world"));
```

Using a type closer to this PR makes these work, but fail other existing valid and important tests, especially this isn't checked anymore:
```js
// $ExpectError Mock function expected to return Promise<number>, not Promise<string>
foo.doAsyncStuff = jest.fn().mockResolvedValue("10");
```

**Comment by julienw** [comment]
This is my current try: https://github.com/flow-typed/flow-typed/compare/master...julienw:jest-resolved-values-fix?expand=1

Various tests are failing... the 2 I was mentioning above, plus new tests failing in latest 2 flow versions :/

**Pull request closed without merging**
