### PR TITLE
Added @material-ui/core Theme & refined withStyles, withTheme etc.

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
Added and improved a bunch of @material-ui/core styling related types. Also added in a few tests to make sure everything is working as expected.

Thanks to @wcandillon for getting me started in the right direction with his existing (on hold) PR (#2152).

### CODE REVIEW

**Comment by wcandillon** [comment]
😍

**Comment by Benjamin-Dobell** [comment]
I've rebased, but please hold off on merging for a little bit as I'm refining some types - specifically making various `*Options` types reject arbitrary keys, and adding a bunch more tests.

**Comment by Benjamin-Dobell** [comment]
Okay, I'm pretty happy with these types and tests now and believe they're ready for review/merging.

**Comment by Benjamin-Dobell** [comment]
By the way, I would have liked to refine some of these types further, but I ran into a road-block with Flow (https://github.com/facebook/flow/issues/6784).

If someone can come up with a way to modify the type definitions in the following [Try Flow](https://flow.org/try/#0C4TwDgpgBAwg9gO2BAHsKBeKBvAbhAJwGcBLRALigQFcBbAI0IF8oB6VqAZTluiLgLo4AMygBjRMjQAacQEMEURlAUhgACxIIA5gChQkKAHkwwMgiKYcAbSLACW7QF1KR+gCsIY4E33hoAGLUCN7mACpyANaO8EiowABKEMDUBAiOJmaIllgAFLFSwACUmAB8xqbmRLq6wsGhiOKIwiTauXCV2a6dFlAAPlBBIVkIEdE6BfFJKWkZPUQl2LpQUCSiuQYQIlAdIzkYWADkdcPmh4vLKzvzVrtVuXiEpBRQAIxMRZe+l6wAVFAAETgUDs1GEogA7iQNNc9gA6BFQX6sXTfCQIFptXJyAjaV6UOwOHSyHHaABMlBoDEIJUpdEYBDKOEu6P4ABsIHC2XA2gAiADq6jkwAA-FAAJpwahQDRS7TqdAASUOABMZVFoHJYJJ4ioEGqCMlUopMlURbzPitWXAOVyebkBRA2WzZCApUpoBCCIhtAi4Xq1W7pWIFId0HYOlBcrg5GySCrhRASrx-QBZahyIVZuQAQgtl0NM0UABYyWwOEYEGyQDL1NBGHYqPSnlBhAIoEHZC0EHwSAQ4aiikA) (without altering the semantics) to make Flow _correctly_ error on that call to `config`, then that would be awesome.

**Comment by Benjamin-Dobell** [comment]
Okay, so I discovered a work around for the aforementioned Flow bug, specifically using `$Shape<Object>` in place of `Object`. It only works in some situations, but it's good for our purposes.

Thus, I've made some of the types stricter, and added tests to validate this, as well as ensured that users can extend these stricter types appropriately (i.e. Custom themes).

**Comment by villesau** [comment]
Looks good @Benjamin-Dobell, keep up the good work!

**Pull request merged**
