### PR TITLE
[ramda_v0.26.x] Refactor pipe() function

### PR DESCRIPTION
**Pull request by retyui**
- Links to documentation: https://ramdajs.com/docs
- Link to GitHub or NPM: https://github.com/ramda/ramda 
- Type of contribution: refactor

Motivation:
There is no possibility to specify the type for incoming arguments and return value:

This RP add this feature:
```js
type State = {
  navigation: {
    componentId: string,
  },
};
// typeof getComponentId === `State => string`
export const getComponentId = pipe<[State], string, _, _, _>(
  prop('navigation'),
  prop('componentId'),
);

```

### CODE REVIEW

**Comment by retyui** [comment]
Blocked by https://github.com/flow-typed/flow-typed/pull/3286

**Comment by retyui** [comment]
@LoganBarnett ^

**Comment by LoganBarnett** [comment]
I'm not sure if Github's interface is being strange or I'm doing something wrong. I see in one case you have a test, but if I ask it to show me the aggregate of all the changes then I don't see the changes to the test suite anymore.

If the test changes were removed, could you comment as to why that was? If possible it would be great to capture something to help enforce these changes. Other than that, this looks good!

**Comment by retyui** [comment]
There is no test changes

**Pull request merged**
