### PR TITLE
[WIP] Add libdef for hoist-non-react-statics_v2.x

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Converted the [`TypeScript` definitions](https://github.com/mridgway/hoist-non-react-statics/blob/master/index.d.ts) to `flow`

Could use some help for the tests tbh (I'm new to creating libdefs so...) 😕😢
@GAntoine Maybe you can point me in the right direction?

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@GAntoine Maybe you can point me in the right direction for some tests?
Or if you're willing to provide them yourself, I wouldn't mind ofcourse 🙂

**Comment by GAntoine** [comment]
I actually took a crack at creating some tests over the weekend but didn't get far. This isn't my field of expertise, but I'll take another look this week.

**Comment by MichaelDeBoey** [comment]
@GAntoine No problem 🙂
I don't use the lib myself, but I came across it, so wanted to contribute it for people who want to use the libdef. 🙂

**Comment by mridgway** [comment]
I have tried adding Flow types to this library, but have not found a way to have it validate the union of the statics of the two components. I'd really appreciate help on this if anyone knows a way to do this.

**Comment by villesau** [comment]
Looks like this already exist at this point -> I'm gonna close this PR. Thanks for the PR @MichaelDeBoey !

**Pull request closed without merging**
