### PR TITLE
WIP: [@material-ui/core_v4.0.0] Add new definition

### PR DESCRIPTION
**Pull request by retyui**
- Links to documentation: https://next.material-ui.com/
- Link to GitHub or NPM: https://github.com/mui-org/material-ui
- Type of contribution: new definition

TODO:

`core/utils/`:
- [x] helpers
- [x] ownerWindow
- [x] reactHelpers
- [x] requirePropFactory

`core/styles/`:
- [x] colorManipulator
- [x] createBreakpoints
- [x] createMixins
- [x] createMuiTheme
- [x] createPalette
- [x] createSpacing
- [x] createStyles
- [x] createTypography
- [x] makeStyles
- [ ] overrides
- [ ] props
- [x] shadows
- [x] shape
- [x] transitions
- [x] useTheme
- [x] withStyles
- [x] withTheme
- [x] zIndex

`core/`:
- [x] AppBar	
- [x] Avatar	
- [x] Backdrop	
- [x] Badge	
- [x] BottomNavigation	
- [x] BottomNavigationAction	
- [x] Box	
- [x] Breadcrumbs	
- [x] Button	
- [x] ButtonBase `50 / 50` %
- [x] Card	
- [x] CardActionArea	
- [x] CardActions	
- [x] CardContent	
- [x] CardHeader	
- [x] CardMedia	
- [x] Checkbox	
- [x] Chip	
- [x] CircularProgress	
- [x] ClickAwayListener	
- [x] Collapse	
- [x] Container	
- [x] CssBaseline	
- [x] Dialog	
- [x] DialogActions	
- [x] DialogContent	
- [x] DialogContentText	
- [x] DialogTitle	
- [x] Divider	
- [x] Drawer	
- [x] ExpansionPanel	
- [x] ExpansionPanelActions	
- [x] ExpansionPanelDetails	
- [x] ExpansionPanelSummary	
- [x] Fab	
- [x] Fade	
- [x] FilledInput	
- [x] FormControl	
- [x] FormControlLabel	
- [x] FormGroup	
- [x] FormHelperText	
- [x] FormLabel	
- [x] Grid	
- [x] GridList	
- [x] GridListTile	
- [x] GridListTileBar	
- [x] Grow	
- [x] Hidden	
- [x] Icon	
- [x] IconButton	
- [x] Input	
- [x] InputAdornment	
- [x] InputBase	
- [x] InputLabel	
- [x] LinearProgress	
- [x] Link	
- [x] List	
- [ ] ListItem	
- [x] ListItemAvatar	
- [x] ListItemIcon	
- [x] ListItemSecondaryAction	
- [x] ListItemText	
- [x] ListSubheader	
- [ ] Menu	
- [ ] MenuItem	
- [ ] MenuList	
- [x] MobileStepper	
- [x] Modal	
- [x] NativeSelect	
- [x] NoSsr	
- [x] OutlinedInput	
- [x] Paper	
- [ ] Popover	
- [ ] Popper	
- [x] Portal	
- [x] Radio	
- [x] RadioGroup	
- [ ] RootRef	
- [ ] Select	
- [x] Slide	
- [ ] Snackbar	
- [ ] SnackbarContent	
- [ ] Step	
- [ ] StepButton	
- [ ] StepConnector	
- [ ] StepContent	
- [ ] StepIcon	
- [ ] StepLabel	
- [ ] Stepper	
- [x] SvgIcon	
- [ ] SwipeableDrawer	
- [ ] Switch	
- [ ] Tab	
- [ ] Table	
- [x] TableBody	
- [ ] TableCell	
- [x] TableFooter	
- [x] TableHead	
- [ ] TablePagination	
- [x] TableRow	
- [x] TableSortLabel	
- [ ] Tabs	
- [ ] TextField	
- [x] Toolbar	
- [x] Tooltip	
- [x] Typography	
- [x] Zoom	
- [x] internal/SwitchBase	
- [ ] useMediaQuery	
- [ ] useScrollTrigger
- [ ] withMobileDialog	
- [ ] withWidth	
- [x] OverridableComponent `50 / 50` %

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Nice work so far. Would you mind fixing up the failing Travis tests while you're at it?

**Comment by retyui** [comment]
I am now describing the types for `@material-ui/сore/style` the following commit will fix the failing Travis

**Comment by AndrewSouthpaw** [comment]
Let me know if you ever want to merge in any of the WIP. Otherwise I'll let you keep working on it until you take off WIP status.

**Comment by retyui** [comment]
When I finish I will let you know

**Comment by retyui** [comment]
I cleaned old branches in fork repo and accidentally deleted this branch)
@AndrewSouthpaw Can you reopen PR?

**Comment by retyui** [comment]
> ada3257

**Comment by retyui** [comment]
@AndrewSouthpaw em...
 What for?

**Comment by AndrewSouthpaw** [comment]
ACK! I'm sorry. :-( I didn't realize this was still a WIP, I was running through PRs and picked this one up.

**Comment by AndrewSouthpaw** [comment]
We can either revert or you can spin up a new PR. Prefs?

**Comment by retyui** [comment]
Revert 
would be better

**Comment by AndrewSouthpaw** [comment]
Doing, will let the tests run and then merge it in.

**Comment by AndrewSouthpaw** [comment]
Done.

**Comment by AndrewSouthpaw** [comment]
Unfortunately I don't think you can "unmerge" a PR so you'll need to open a fresh one.

**Pull request merged**
