### PR TITLE
[jest_v24.x.x] Add definitions

### PR DESCRIPTION
**Pull request by pascalduez**
- Links to documentation: https://github.com/facebook/jest/blob/master/CHANGELOG.md
- Link to GitHub or NPM: https://github.com/facebook/jest
- Type of contribution: addition 

Other notes:
This is essentially a copy of the `v23.x.x` definitions with new additions and fixes.
- [x] test.todo
- [x] jest.isolateModules
- [x] jest.getTimerCount

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Looks good, are the errors pre-existing?

**Comment by pascalduez** [comment]
> are the errors pre-existing?

Yes, we have this on almost all our libdefs since Flow 0.75, when `Object`, `Function` was aliased to `any`, so lots of `// $ExpectError` tests are no longer true.

**Comment by pascalduez** [comment]
To Review! 
Split into commits for easier review.

**Comment by villesau** [comment]
@pascalduez LGTM. Is there still something you are adding here?

**Comment by pascalduez** [comment]
@villesau I'm done ;)

**Pull request merged**
