### PR TITLE
fix(ramda): allow pipeK as inferred type

### PR DESCRIPTION
**Pull request by naterious**

### CODE REVIEW

**Comment by retyui** [comment]
This method `pipeK()` will `Deprecated since v0.26.0`

**Comment by retyui** [comment]
@AndrewSouthpaw
I think you can close this PR )

**Comment by AndrewSouthpaw** [comment]
Well, it doesn't make it any worse, so I'm fine with it in this case. 

@LoganBarnett anything to add?

**Comment by LoganBarnett** [comment]
@AndrewSouthpaw I don't see any harm in adding it either.

Re: Deprecation I did notice that we have a few functions in the libdef that have been deprecated _and removed_ from Ramda. We should consider splitting the Ramda versions. That said, the matrix of files we have to support with just a "head" version of Ramda is getting cumbersome. I'll write up a ticket for it and elaborate more there.

**Comment by AndrewSouthpaw** [comment]
K, LGTM, but conflicts will need to be resolved before continuing.

**Comment by AndrewSouthpaw** [comment]
Closing due to inactivity. Feel free to respond to reopen.

**Pull request closed without merging**
