### PR TITLE
[CLI] Fix runTests on Windows

### PR DESCRIPTION
**Pull request by moroine**
- Type of contribution: FIX

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Can you provide a screenshot or something demonstrating it works now? I don't have windows. 😆

**Comment by moroine** [comment]
Before:
render1563324202742

> It was somehow opening Atom on my laptop

After:
render1563322284157

**Comment by moroine** [comment]
@AndrewSouthpaw any update?

**Comment by AndrewSouthpaw** [comment]
Sorry! Looks great.

**Comment by AndrewSouthpaw** [comment]
cc @GAntoine to release a new version bump of the cli.

**Comment by AndrewSouthpaw** [comment]
@moroine fyi we've released a new version of the CLI with this fix. Thanks!

**Comment by moroine** [comment]
Awesome thanks,

**Pull request merged**
