### PR TITLE
[ci/cd] Post eslint warnings for defintions

### LINKED ISSUE #49: [Test CI] Automatically comment on PRs that add `any` types
We want the libdefs in this repository to remain high quality. As such, we want to minimize `any` types as much as is reasonably possible. In some cases an `any` type of some kind (including things like `Object`, `Function`, etc) is unavoidable -- so we can't simply ban them altogether.

To minimize the number of unnecessary `any` types, it would be good to have Travis check for these and comment on any pull requests that add them -- pointing out that they should be avoided if at all possible.

Perhaps something like a `--strict` flag could be added to the `validate-defs` command that emits warnings on these kinds of things?

### PR DESCRIPTION
**Pull request by Brianzchen**
Closes #49

With the introduction of github actions, eslint will automatically add inline errors to the PR to give really good visual feedback for when a change has linting errors

### CODE REVIEW

**Comment by Brianzchen** [comment]
node_setup which automatically annotates github prs doesn't annotate warnings, so looking into that

**Comment by Brianzchen** [comment]
@GAntoine I'm quite close to getting this action to work as I expect but I'm missing a key part where the `GITHUB_TOKEN` doesn't have permission to submit annotations, you can see the error [here](https://github.com/flow-typed/flow-typed/runs/4733011475?check_suite_focus=true#step:7:9) could we enable it to see if I'm able to get it working?

**Comment by Brianzchen** [comment]
Cannot write checks using annotate tool because all forked public repos can only have read permission
ref: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

**Comment by GAntoine** [comment]
@Brianzchen Can you create a branch in this repo directly and try again? We can delete the branch after it's been merged.

**Comment by Brianzchen** [comment]
This will be handled by flow-typed-pr-bot instead

**Pull request closed without merging**
