### PR TITLE
react-dnd definition: Add DragDropContextProvider

### PR DESCRIPTION
**Pull request by B-Reif**
Adds a definition for react-dnd's DragDropContextProvider component.

Here's the component's docs:
http://react-dnd.github.io/react-dnd/docs-drag-drop-context-provider.html

And its source:
https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/DragDropContextProvider.js

The prop typing mirrors the source's PropTypes. Let me know if anything is missing.

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Probably fell through the cracks. :-) You'll need to fix the CI errors before it can be merged.

**Comment by janpaul123** [comment]
Maybe rebase so the travis build runs again (right now it's a dead link)? 😄

**Comment by AndrewSouthpaw** [comment]
Yeah, this PR is from before the org change, so it'll need to be rerun. A rebase would suffice.

**Comment by villesau** [comment]
This now exists in the react-dnd_v2.x.x.js, thanks for the initial work @B-Reif !

**Pull request closed without merging**
