### PR TITLE
Revert "[sequelize_v4] fix: Convert module from ESM to CommonJS"

### PR DESCRIPTION
**Pull request by pascalduez**
Reverts flow-typed/flow-typed#3276

### CODE REVIEW

**Comment by jedwards1211** [comment]
thanks, i was intending to make myself earlier but somehow failed to fetch the commit in question so that I could revert it

**Comment by pascalduez** [comment]
@jedwards1211 Tests are failing (recent Flow versions), if I'm merging we should have a follow-up PR to update it. Or at least scope the def to lower Flow versions, WDYT?

**Comment by jedwards1211** [comment]
let me take a look

**Comment by pascalduez** [comment]
There's `$Subtype` and probably `Function`.

**Comment by jedwards1211** [comment]
Some of the errors are due to flow's ever-increasing bugs.  For example, it's not our fault that Flow is failing to decide which case to select below (there's no way the object literal could be a function)

```
    Error ---------------------------------------------------------------------------------------- test_sequelize.js:1574:16
    
    Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
    fix add a type annotation to array literal [3].
    
       test_sequelize.js:1574:16
                            v
       1574|     reversed : {
       1575|       order : [['id', 'DESC']]
       1576|     }
                 ^
    
    References:
       sequelize_v4.x.x.js:5278:26
       5278|     [scopeName: string]: AnyFindOptions | Function
                                      ^^^^^^^^^^^^^^ [1]
       sequelize_v4.x.x.js:5278:43
       5278|     [scopeName: string]: AnyFindOptions | Function
                                                       ^^^^^^^^ [2]
       test_sequelize.js:1575:15
       1575|       order : [['id', 'DESC']]
                           ^^^^^^^^^^^^^^^^ [3]
```

**Comment by jedwards1211** [comment]
I can make a follow-up PR to replace `$Subtype` and `Function` though

**Comment by jedwards1211** [comment]
Do you have any idea how to refine member types in derived classes?  When I get rid of `$Subtype` it complains about `BelongsTo` declaring `associationType: 'BelongsTo'` whereas the base class (`Association`) declares `associationType: 'BelongsTo' | 'HasOne' | ...`

**Comment by jedwards1211** [comment]
Nevermind, changing to covariant `+associationType` in the base and derived classes fixes it

**Pull request merged**
