### PR TITLE
[mocha_v6.x] Add definitions for mocha v6 (taken from mocha_v5.x)

### PR DESCRIPTION
**Pull request by AVykhrystyuk**
- Links to documentation: https://github.com/mochajs/mocha
- Link to GitHub or NPM: https://github.com/mochajs/mocha
- Type of contribution: new definition

### CODE REVIEW

**Comment by pascalduez** [comment]
Thanks for hte PR!  
Could you detail a bit any additions/changes if any? 
Actually, the best when copying an exiting definitions, is to split the actions into commits. 
One commit for copying/bumping, other ones for updates.

**Comment by AlexeyVykhrystyuk-GB** [comment]
> Actually, the best when copying an exiting definitions, is to split the actions into commits.

Ahh sorry for that, for sure will do it next time the way you described

There was not changes at all, this is just a copy of mocha_v5.x with bumping

**Comment by AVykhrystyuk** [comment]
> Actually, the best when copying an exiting definitions, is to split the actions into commits.

Ahh sorry for that, for sure will do it next time the way you described

There were no changes at all, this is just exact copy of mocha_v5.x with the version bumping

**Comment by pascalduez** [comment]
> There were no changes at all, this is just exact copy of mocha_v5.x with the version bumping

All right, thanks!

**Pull request merged**
