### PR TITLE
feat(redux-saga_v0.16): update delay signature

### PR DESCRIPTION
**Pull request by ADagen**
Redux-saga's `delay` allows to return a Promise that will resolve after ms milliseconds with val: https://redux-saga.js.org/docs/api/#delayms-val

### CODE REVIEW

**Comment by ADagen** [comment]
What's wrong with Travis pipelines?

**Comment by GAntoine** [comment]
Seems like the current definitions is broken for versions 62+

**Comment by andrei-hameza** [comment]
As for me it makes sense to reuse definition for `delay` from here https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux-saga_v0.13.x/flow_v0.38.x-/redux-saga_v0.13.x.js#L119 It fits better.

**Comment by AndrewSouthpaw** [comment]
Looks like the build is still failing, can you dig into it?

**Comment by ADagen** [comment]
Yep, I'm going to investigate the case this evening)

**Comment by GAntoine** [comment]
Closed in favour of #2502

**Pull request closed without merging**
