### PR TITLE
Add pull streams definition.

### PR DESCRIPTION
**Pull request by Gozala**
Please note that I run into #1724 and there for pull contains test file that is supposed to fail, but it isn't failing for whatever reason. Another odd thing is that I'm using  `import type { Callback } from "callback.flow"` in my libdef, I can't figure out how to actually depend on other library, but for whatever reason that does not seems to fail either.

### CODE REVIEW

**Comment by Gozala** [comment]
This project appears to be dead and so does #flow IRC channel so I'm giving up on trying to get tests running. I have updated this pull removing all tests, if anyone ever get back to me I'll try to work out solution otherwise I don't waste any more time on this. Given that are ton of open pull requests I suspect this is not going to merge anytime soon.

**Comment by GAntoine** [comment]
Hey @Gozala, I'm sorry to hear you feel that way about this project. I can tell you it's not dead; the nature of the repo means there's more of hum then a buzz around here. I check in every couple days to clean up issues and merge passing PRs.

> Another odd thing is that I'm using import type { Callback } from "callback.flow" in my libdef, I can't figure out how to actually depend on other library

Try placing that line inside of a `declare module`, and let me know if that makes any difference.

> Please note that I run into #1724 and there for pull contains test file that is supposed to fail, but it isn't failing for whatever reason.

I've copied over this PR and tweaked it to have the tests run. Give me a couple minutes and I'll open a PR. As a note, flow version `0.63` is not yet a valid version.

**Comment by GAntoine** [comment]
Right, you can take a look at GAntoine/flow-typed/pull/8

There's a parsing error with the file which causes linting to fail, but if you run `flow-typed run-tests pull-stream`, they'll run (and succeed) as expected.

**Comment by Gozala** [comment]
> Hey @Gozala, I'm sorry to hear you feel that way about this project. I can tell you it's not dead; the nature of the repo means there's more of hum then a buzz around here. I check in every couple days to clean up issues and merge passing PRs.

@GAntoine I apologize, I clearly overreacted, I just had being having hard time lately getting any help on #flow channel and seeing pulls open since June clouded my judgment. Thanks for getting back.

> Try placing that line inside of a declare module, and let me know if that makes any difference.

It's not that it does not work, it's just unclear what the behavior would be if `callback.flow` package isn't installed in the project were this types are pulled into. Is there a way to define dependencies across package boundaries with flow typedefs ?

> I've copied over this PR and tweaked it to have the tests run. Give me a couple minutes and I'll open a PR. As a note, flow version 0.63 is not yet a valid version.

Why isn't it valid ? Current release version on npm is 0.63.1. Do you mean it's not yet supported by `flow-typed` ? If so what version should I use ?

**Comment by Gozala** [comment]
> Right, you can take a look at GAntoine/flow-typed#8
> 
> There's a parsing error with the file which causes linting to fail, but if you run flow-typed run-tests pull-stream, they'll run (and succeed) as expected.

Thanks @GAntoine problem I encounter is that even if I remove `// $ExpectError` it still succeeds, in fact I am just unable to make it fail.

**Comment by GAntoine** [comment]
No worries! Frustration is a devil in all of us.

> seeing pulls open since June

Any PR older then December is there for historical reasons, or as a WIP. I did a purge sometime early December.

> It's not that it does not work, it's just unclear what the behavior would be if callback.flow package isn't installed in the project were this types are pulled into.

Anything imported will be typed as `any`, as a catch-all.

> Is there a way to define dependencies across package boundaries with flow typedefs?

I get that a lot, but I don't have a clear answer for you. That's a question to ask the flow team. You can ask them directly on the facebook/flow repo.

> Why isn't it valid ? Current release version on npm is 0.63.1. Do you mean it's not yet supported by flow-typed ? If so what version should I use ?

Now that right there is the real weirdness here. It seems to not be fetching any releases after `61.0` Let me take a look and maybe talk to the team, and I'll get back to you in #1724

>  problem I encounter is that even if I remove // $ExpectError it still succeeds, in fact I am just unable to make it fail.

If you clone/copy my PR (file name and structure) and run `flow-typed run-tests pull-stream`, what do you see? You should see the following:

```
Running definition tests in /Users/georges-antoine/workspace/flow-typed/definitions/npm...

Fetching all Flow binaries...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.55.0)...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.56.0)...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.57.1)...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.57.2)...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.57.3)...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.58.0)...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.59.0)...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.60.0)...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.60.1)...
Testing pull-stream_v3.x.x/flow_v0.55.x- (flow-v0.61.0)...

All tests passed!
```

Run it both with and without `ExpectError`, and paste the output.

**Comment by Gozala** [comment]
I actually reported that issue as #1724. Oddly if I run `travis.sh` it fails without any of my changes and with the same flow / node versions as it runs on travis. If just run `flow-typed run-tests` or `node ./cli/dist/cli.js run-tests` and with this version https://github.com/flowtype/flow-typed/pull/1725/commits/40af6339e7a9f2f1ef120f67742094a6736fe392 it does pass on my machine but failed as expected on travis https://travis-ci.org/flowtype/flow-typed/jobs/327897772

**Comment by Gozala** [comment]
> If you clone/copy my PR (file name and structure) and run flow-typed run-tests pull-stream, what do you see? You should see the following:

I get this in both cases:

```js
flow-typed run-tests pull-stream
Running definition tests in /Users/gozala/Projects/flow-typed/definitions/npm...

Fetching all Flow binaries...

All tests passed!
```

I can see from your output that it actually does not test anything

**Comment by Gozala** [comment]
> Now that right there is the real weirdness here. It seems to not be fetching any releases after 61.0 Let me take a look and maybe talk to the team, and I'll get back to you in #1724

It seem from the output in travis that it actually (does run 0.63.1 there)[https://travis-ci.org/flowtype/flow-typed/jobs/327897772#L923]

**Comment by villesau** [comment]
@Gozala what is the status of this? Any progress? :)

**Comment by Gozala** [comment]
@villesau well I was unable to get tests to fail & only reason I actually wrote these typedfs was so I could pull them into some other project that used pull streams which  did not end up integrating flow into toolchain, so I have very little motivation & not much free time.

I’d love if someone would take over this and get it to a finish line.

**Comment by villesau** [comment]
I assume this is not moving forward -> closing. Feel free to reopen!

**Pull request closed without merging**
