### PR TITLE
Needed change for flow 0.82.0

### PR DESCRIPTION
**Pull request by doberkofler**

### CODE REVIEW

**Comment by GAntoine** [comment]
Looks like this change broke the specs. Also, if this is indeed needed for 0.82.x, might make sense to create a new folder called `flow_v0.82.x-`, cap the current one at `flow_v0.58.x-v0.81.x`

**Comment by doberkofler** [comment]
Correct, but in my understanding the change would also work in older versions.

**Comment by GAntoine** [comment]
Ok cool, then it's just the specs that need to be addressed.

**Comment by GAntoine** [comment]
Closing as already complete.

**Pull request closed without merging**
