### PR TITLE
Fix Backbone Collection methods

### PR DESCRIPTION
**Pull request by thekondr**
Links to documentation:

- returns from set: https://backbonejs.org/docs/backbone.html#section-123
- add: https://backbonejs.org/docs/backbone.html#section-113
- reset: https://backbonejs.org/docs/backbone.html#section-123
- remove: https://backbonejs.org/docs/backbone.html#section-114

Link to GitHub: https://github.com/jashkenas/backbone/
Type of contribution: fix

### CODE REVIEW

**Comment by pascalduez** [comment]
Someone willing to address the failing tests as well?

**Comment by thekondr** [comment]
The tests are failing for a different reason, and should probably be fixed in another PR.

**Comment by EvgeneOskin** [comment]
Thanks, @thekondr! 
@pascalduez this change looks good to me.

**Pull request merged**
