### PR TITLE
Add definition for bignumber.js

### PR DESCRIPTION
**Pull request by Akurganow**
Adds library definition for https://github.com/MikeMcl/bignumber.js

### CODE REVIEW

**Comment by Akurganow** [comment]
@GAntoine done

**Comment by GAntoine** [comment]
@Akurganow My bad, I meant `flow_v0.25.x-`, notice the `v`.

**Comment by Akurganow** [comment]
@GAntoine done again :)

**Comment by GAntoine** [comment]
Well it seems that the package name is causing issues with the CLI... I'm not sure how to move this forward, so I'm putting it on hold in the meantime.

**Comment by GAntoine** [comment]
Closing in favour of #2505

**Pull request closed without merging**
