### PR TITLE
[react-navigation] Replace $Shape with $Rest<T, {...}>

### PR DESCRIPTION
**Pull request by Ashoat**
Putting this PR up to get feedback. Is this a wise change to make? `$Shape` seems to have all sorts of issues, and it appears that the hack using `$Rest` is a good workaround.

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Seems reasonable? I haven't used that `$Rest` workaround before so I don't have a whole lot to add unfortunately, but if it addresses certain problems and the tests still pass then I'd call this good.

**Comment by AndrewSouthpaw** [comment]
If you're feeling good about it, let me know and I'll go ahead and merge it.

**Comment by Ashoat** [comment]
Let's do it. If it introduces issues we can revert

**Review by pascalduez — APPROVED** [review]

**Comment by jedwards1211** [comment]
I just managed to solve a complex problem I worried was impossible for months with this `$Rest` workaround, and got flow checks to pass on 0.84, 0.120, and 0.141, so I guess we can trust this workaround.  Here's my crazy use case...working on declaring validator objects and extracting the corresponding flow types from them:

```js

type ExtractPropertyTypes<P: { [any]: Type<any> }> = $ObjMap<
  P,
  <V>(Type<V>) => V
>
type ExtractOptionalPropertyTypes<P: { [any]: Type<any> }> = $Rest<
  ExtractPropertyTypes<P>,
  {}
>

declare export function object<R: { [any]: Type<any> }>({|
  required: R,
  exact: false,
|}): Type<{ ...ExtractPropertyTypes<R> }>
declare export function object<R: { [any]: Type<any> }>({|
  required: R,
  exact?: true,
|}): Type<$Exact<ExtractPropertyTypes<R>>>
declare export function object<S: { [any]: Type<any> }>({|
  optional: S,
  exact: false,
|}): Type<{ ...ExtractOptionalPropertyTypes<S> }>
declare export function object<S: { [any]: Type<any> }>({|
  optional: S,
  exact?: true,
|}): Type<$Exact<ExtractOptionalPropertyTypes<S>>>
declare export function object<
  R: { [any]: Type<any> },
  S: { [any]: Type<any> }
>({|
  required: R,
  optional: S,
  exact: false,
|}): Type<{
  ...$Exact<ExtractPropertyTypes<R>>,
  ...$Exact<ExtractOptionalPropertyTypes<S>>,
}>
declare export function object<
  R: { [any]: Type<any> },
  S: { [any]: Type<any> }
>({|
  required: R,
  optional: S,
  exact?: true,
|}): Type<{|
  ...$Exact<ExtractPropertyTypes<R>>,
  ...$Exact<ExtractOptionalPropertyTypes<S>>,
|}>
declare export function object<R: { [any]: Type<any> }>(
  required: R
): Type<$Exact<ExtractPropertyTypes<R>>>
```

```js
// @flow

import * as t from '../src/index'
import { describe, it } from 'mocha'

describe('inexact', () => {
  it('required only', () => {
    const PersonType = t.object({
      required: { name: t.string() },
      exact: false,
    })

    type Person = t.ExtractType<typeof PersonType>

    const a: Person = { name: 'foo' }
    const b: Person = { name: 'foo', age: 2 }
    const c: Person = { name: 'foo', age: 2, bar: 'baz' }

    // $FlowFixMe
    const d: Person = { age: 2 }
    // $FlowFixMe
    const e: Person = { name: 2 }
    // $FlowFixMe
    const f: Person = { name: 'foo', age: '2' }
    // $FlowFixMe
    const g: Person = 2
  })
  it('optional only', () => {
    const PersonType = t.object({
      optional: { name: t.string(), age: t.number() },
      exact: false,
    })

    type Person = t.ExtractType<typeof PersonType>

    const a: Person = { name: 'foo' }
    const b: Person = { name: 'foo', age: 2 }
    const c: Person = { name: 'foo', age: 2, bar: 'baz' }
    const d: Person = { bar: 'baz' }
    const e: Person = { age: 2 }

    // $FlowFixMe
    const f: Person = { name: 2 }
    // $FlowFixMe
    const g: Person = { name: 'foo', age: '2' }
    // $FlowFixMe
    const h: Person = 2
  })
  it('required and optional', () => {
    const PersonType = t.object({
      required: { name: t.string() },
      optional: { age: t.number() },
      exact: false,
    })

    type Person = t.ExtractType<typeof PersonType>

    const a: Person = { name: 'foo' }
    const b: Person = { name: 'foo', age: 2 }
    const c: Person = { name: 'foo', age: 2, bar: 'baz' }

    // $FlowFixMe
    const d: Person = { age: 2 }
    // $FlowFixMe
    const e: Person = { name: 2 }
    // $FlowFixMe
    const f: Person = { name: 'foo', age: '2' }
    // $FlowFixMe
    const g: Person = 2
  })
})
describe('exact', () => {
  it('required only', () => {
    const PersonType = t.object({
      required: { name: t.string() },
    })

    type Person = t.ExtractType<typeof PersonType>

    const a: Person = { name: 'foo' }
    // $FlowFixMe
    const b: Person = { name: 'foo', age: 2 }
    // $FlowFixMe
    const c: Person = { name: 'foo', age: 2, bar: 'baz' }
    // $FlowFixMe
    const d: Person = { age: 2 }
    // $FlowFixMe
    const e: Person = { name: 2 }
    // $FlowFixMe
    const f: Person = { name: 'foo', age: '2' }
    // $FlowFixMe
    const g: Person = 2
  })
  it('required only -- shortcut', () => {
    const PersonType = t.object({
      name: t.string(),
    })

    type Person = t.ExtractType<typeof PersonType>

    const a: Person = { name: 'foo' }
    // $FlowFixMe
    const b: Person = { name: 'foo', age: 2 }
    // $FlowFixMe
    const c: Person = { name: 'foo', age: 2, bar: 'baz' }
    // $FlowFixMe
    const d: Person = { age: 2 }
    // $FlowFixMe
    const e: Person = { name: 2 }
    // $FlowFixMe
    const f: Person = { name: 'foo', age: '2' }
    // $FlowFixMe
    const g: Person = 2
  })
  it('optional only', () => {
    const PersonType = t.object({
      optional: { name: t.string(), age: t.number() },
    })

    type Person = t.ExtractType<typeof PersonType>

    const a: Person = { name: 'foo' }
    const b: Person = { name: 'foo', age: 2 }
    // $FlowFixMe
    const c: Person = { name: 'foo', age: 2, bar: 'baz' }
    // $FlowFixMe
    const d: Person = { bar: 'baz' }
    const e: Person = { age: 2 }

    // $FlowFixMe
    const f: Person = { name: 2 }
    // $FlowFixMe
    const g: Person = { name: 'foo', age: '2' }
    // $FlowFixMe
    const h: Person = 2
  })
  it('required and optional', () => {
    const PersonType = t.object({
      required: { name: t.string() },
      optional: { age: t.number() },
    })

    type Person = t.ExtractType<typeof PersonType>

    const a: Person = { name: 'foo' }
    const b: Person = { name: 'foo', age: 2 }
    // $FlowFixMe
    const c: Person = { name: 'foo', age: 2, bar: 'baz' }

    // $FlowFixMe
    const d: Person = { age: 2 }
    // $FlowFixMe
    const e: Person = { name: 2 }
    // $FlowFixMe
    const f: Person = { name: 'foo', age: '2' }
    // $FlowFixMe
    const g: Person = 2
  })
})
```

**Comment by AndrewSouthpaw** [comment]
Thanks @jedwards1211. If *sounds* like you're giving a green light as well, though maybe I'm misreading you. I'm going to go ahead and merge, and if I'm way off and you'd like some changes, we can revert and keep iterating.

**Pull request merged**
