### PR TITLE
Change deprecated $call syntax to use callable syntax for axios

### PR DESCRIPTION
**Pull request by benjreinhart**
Addresses #2405. I think I used the right naming conventions but could use some eyes to make sure I did this right.

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
You need to cap the flow versions, so you have only one open flow version range folder. See other libdefs for examples. LMK if you have questions. :)

**Comment by benjreinhart** [comment]
@AndrewSouthpaw thanks for the reply. Can you be more specific though, I thought I did what you're saying. [This example](https://github.com/flowtype/flow-typed/tree/master/definitions/npm/styled-components_v3.x.x) looks like the same as what I've done here?

**Comment by AndrewSouthpaw** [comment]
change_deprecated__call_syntax_to_use_callable_syntax_for_axios_by_benjreinhart_ _pull_request__2424_ _flowtype_flow-typed

**Comment by benjreinhart** [comment]
@AndrewSouthpaw hmm interesting... that's precisely what I've done here, is it not showing that to you?

Here is my branch that I'm trying to merge into this repo with:

https://github.com/benjreinhart/flow-typed/tree/master/definitions/npm/axios_v0.13.x
https://github.com/benjreinhart/flow-typed/tree/master/definitions/npm/axios_v0.15.x
https://github.com/benjreinhart/flow-typed/tree/master/definitions/npm/axios_v0.16.x
https://github.com/benjreinhart/flow-typed/tree/master/definitions/npm/axios_v0.17.x

**Comment by AndrewSouthpaw** [comment]
`¯\_(ツ)_/¯`

Are you sure this PR is up to date? I'm looking at the diff and that's where I got that screenshot from.

**Comment by benjreinhart** [comment]
Weird... it shows it to me in the diff. Are you using something other than the web ui?

screen_shot_2018-06-29_at_3_41_42_pm

I do not, however, know why the build is failing.

**Comment by nesl247** [comment]
Any update on this?

**Comment by AndrewSouthpaw** [comment]
I'm noticing there's also some merge conflicts...

**Comment by AndrewSouthpaw** [comment]
I'm gonna treat this PR is closed, feel free to ping if you want to revitalize it.

**Pull request closed without merging**
