### PR TITLE
fix react testing library act() to work fine in flow >=0.153

### PR DESCRIPTION
**Pull request by atabel**
This fixes this issue when trying to use react testing library `act()` with async functions in flow 0.153:
image

This new error is caused by these new changes in flow: https://medium.com/flow-type/sound-typing-for-this-in-flow-d62db2af969e

- Links to documentation: 
- Link to GitHub or NPM: 
- Type of contribution: fix

Other notes:

### CODE REVIEW

**Comment by Brianzchen** [comment]
@atabel there's a minor amount of suppression errors on react-dom_v16. Would you mind fixing this too so it's easier to review? ref: https://github.com/flow-typed/flow-typed/pull/4102/checks?check_run_id=2930512216#step:5:1248

**Review by Brianzchen — APPROVED** [review]
LGTM

**Comment by pascalduez** [comment]
Funny, I gave it a try, but could not make the test `act(() => Promise.resolve())` to pass under 0.154.
Happy to see this fixed, thanks.

Could you please split this into commits though? One for react-testing, and one for react-dom.

**Comment by atabel** [comment]
@pascalduez, what do you mean? split this in two different PRs? or somehow rewrite the history of this branch to split in different commits?

**Comment by pascalduez** [comment]
> @pascalduez, what do you mean? split this in two different PRs? or somehow rewrite the history of this branch to split in different commits?

As you prefer, two commits in this present PR will be fine.

**Comment by atabel** [comment]
ok, done. @pascalduez, is this ok now?

**Pull request merged**
