### PR TITLE
Redux saga v1

### PR DESCRIPTION
**Pull request by retyui**
# `redux-saga/index.js` :heavy_check_mark: 
## Types
  - [x] detach
  - [x] CANCEL
  - [x] SAGA_LOCATION
  - [x] buffers
  - [x] default
  - [x] runSaga
  - [x] END
  - [x] isEnd
  - [x] eventChannel
  - [x] channel
  - [x] multicastChannel
  - [x] stdChannel
## Tests
  - [x] detach
  - [x] CANCEL
  - [x] SAGA_LOCATION
  - [x] buffers
  - [x] default
  - [x] runSaga
  - [x] END
  - [x] isEnd
  - [x] eventChannel
  - [x] channel
  - [x] multicastChannel
  - [x] stdChannel

---

# `redux-saga/effects` - :heavy_check_mark: 
## Types
  - [x] actionChannel
  - [x] all
  - [x] apply
  - [x] call
  - [x] cancel
  - [x] cancelled
  - [x] cps
  - [x] debounce
  - [x] delay
  - [x] flush
  - [x] fork
  - [x] getContext
  - [x] join
  - [x] put
  - [x] putResolve
  - [x] race
  - [x] retry
  - [x] select
  - [x] setContext
  - [x] spawn
  - [x] take
  - [x] takeEvery
  - [x] takeLatest
  - [x] takeLeading
  - [x] takeMaybe
  - [x] throttle
## Tests
  - [x] actionChannel
  - [x] all
  - [x] apply
  - [x] call
  - [x] cancel
  - [x] cancelled
  - [x] cps
  - [x] debounce
  - [x] delay
  - [x] flush
  - [x] fork
  - [x] getContext
  - [x] join
  - [x] put
  - [x] putResolve
  - [x] race
  - [x] retry
  - [x] select
  - [x] setContext
  - [x] spawn
  - [x] take
  - [x] takeEvery
  - [x] takeLatest
  - [x] takeLeading
  - [x] takeMaybe
  - [x] throttle

### CODE REVIEW

**Comment by retyui** [comment]
**Help** who know how fix this [error](https://travis-ci.org/flow-typed/flow-typed/jobs/437969773) ?
<details>
  <summary>View error</summary>
```sh
ERROR: redux-saga_v1.x.x/flow_v0.82.0-
 * redux-saga_v1.x.x/flow_v0.82.0- (flow-v0.82.0): Unexpected Flow errors(2):
   Error --------------------------------------------------------------------------- test_redux-saga_1.x.x_runSaga.js:122:5
   
   Could not decide which case to select. Since case 2 [1] may work but if it doesn't case 3 [2] looks promising too. To
   fix add a type annotation to `channel` [3].
   
      test_redux-saga_1.x.x_runSaga.js:122:5
      122|     runSaga({ channel }, s1, "");
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   
   References:
      redux-saga_v1.x.x.js:122:5
               v--------------------------------------
      122|     <A, S, R, T1, Fn: (t1: T1) => Saga<R>>(
      123|       options: RunSagaOptions<A, S>,
      124|       saga: Fn,
      125|       t1: T1
      126|     ): Task<R>,
               ---------^ [1]
      redux-saga_v1.x.x.js:127:5
               v--------------------------------------------------
      127|     <A, S, R, T1, T2, Fn: (t1: T1, t2: T2) => Saga<R>>(
      128|       options: RunSagaOptions<A, S>,
      129|       saga: Fn,
      130|       t1: T1,
      131|       t2: T2
      132|     ): Task<R>,
               ---------^ [2]
      test_redux-saga_1.x.x_runSaga.js:122:15
      122|     runSaga({ channel }, s1, "");
                         ^^^^^^^ [3]
   
   
   
   Found 1 error
   
   null
```
</details>

**Comment by retyui** [comment]
This PR will add types for latest version `redux-saga@beta-3` [API](https://github.com/redux-saga/redux-saga/tree/master/docs/api#takeeverypattern-saga-args)

**Comment by retyui** [comment]
@GAntoine 
@villesau 
I almost finished, but I can’t solve this problem : https://github.com/flow-typed/flow-typed/pull/2768#issuecomment-427570878
Do you have any idea how to solve it?

**Comment by villesau** [comment]
@retyui wow, awesome work!! Unfortunately I'm not redux-saga user so I can do any thorough smoke testing agains any existing project. I can go trough the changes but it won't happen over night, there are quite a bunch of them :D

**Comment by villesau** [comment]
@retyui yeah that's known issue :( see https://github.com/flow-typed/flow-typed/issues/2916

**Comment by villesau** [comment]
@retyui Finally the CI is fixed and the build passed, awesome work, thanks!! 💯

**Comment by retyui** [comment]
@villesau :+1: Good job! Thank you)

**Pull request merged**
