### PR TITLE
WIP: [@material-ui/core_v4.0.0] Add new definition

### PR DESCRIPTION
**Pull request by retyui**
- Links to documentation: https://next.material-ui.com/
- Link to GitHub or NPM: https://github.com/mui-org/material-ui
- Type of contribution: new definition

---

- [ ] Unlock flow version

--- 

TESTS: 

- [ ] LinearProgress
- [x] List
- [ ] ListItemAvatar
- [ ] ListItemIcon
- [ ] ListItemText
- [ ] ListItemSecondaryAction
- [ ] ListSubheader
- [ ] MobileStepper
- [ ] OutlinedInput
- [ ] Radio
- [ ] RadioGroup
- [ ] Tooltip
- [ ] Toolbar
- [ ] TableRow
- [ ] Menu

TODO:

`core/utils/`:
- [x] helpers
- [x] ownerWindow
- [x] reactHelpers
- [x] requirePropFactory

`core/styles/`:
- [x] colorManipulator
- [x] createBreakpoints
- [x] createMixins
- [x] createMuiTheme
- [x] createPalette
- [x] createSpacing
- [x] createStyles
- [x] createTypography
- [x] makeStyles
- [ ] overrides
- [ ] props
- [x] shadows
- [x] shape
- [x] transitions
- [x] useTheme
- [x] withStyles
- [x] withTheme
- [x] zIndex

`core/`:
- [x] AppBar	
- [x] Avatar	
- [x] Backdrop	
- [x] Badge	
- [x] BottomNavigation	
- [x] BottomNavigationAction	
- [ ] Box	
- [x] Breadcrumbs	
- [x] Button	
- [x] ButtonBase `50 / 50` %
- [x] Card	
- [x] CardActionArea	
- [x] CardActions	
- [x] CardContent	
- [x] CardHeader	
- [x] CardMedia	
- [x] Checkbox	
- [x] Chip	
- [x] CircularProgress	
- [x] ClickAwayListener	
- [x] Collapse	
- [x] Container	
- [x] CssBaseline	
- [x] Dialog	
- [x] DialogActions	
- [x] DialogContent	
- [x] DialogContentText	
- [x] DialogTitle	
- [x] Divider	
- [x] Drawer	
- [x] ExpansionPanel	
- [x] ExpansionPanelActions	
- [x] ExpansionPanelDetails	
- [x] ExpansionPanelSummary	
- [x] Fab	
- [x] Fade	
- [x] FilledInput	
- [x] FormControl	
- [x] FormControlLabel	
- [x] FormGroup	
- [x] FormHelperText	
- [x] FormLabel	
- [x] Grid	
- [x] GridList	
- [x] GridListTile	
- [x] GridListTileBar	
- [x] Grow	
- [x] Hidden	
- [x] Icon	
- [x] IconButton	
- [x] Input	
- [x] InputAdornment	
- [x] InputBase	
- [x] InputLabel	
- [x] LinearProgress	
- [x] Link	
- [x] List	
- [x] ListItem	
- [x] ListItemAvatar	
- [x] ListItemIcon	
- [x] ListItemSecondaryAction	
- [x] ListItemText	
- [x] ListSubheader	
- [x] Menu	
- [x] MenuItem	
- [x] MenuList	
- [x] MobileStepper	
- [x] Modal	
- [x] NativeSelect	
- [x] NoSsr	
- [x] OutlinedInput	
- [x] Paper	
- [x] Popover	
- [x] Popper	
- [x] Portal	
- [x] Radio	
- [x] RadioGroup	
- [x] RootRef	
- [x] Select	
- [x] Slide	
- [ ] Snackbar	
- [ ] SnackbarContent	
- [ ] Step	
- [ ] StepButton	
- [ ] StepConnector	
- [ ] StepContent	
- [ ] StepIcon	
- [ ] StepLabel	
- [ ] Stepper	
- [x] SvgIcon	
- [ ] SwipeableDrawer	
- [ ] Switch	
- [ ] Tab	
- [ ] Table	
- [x] TableBody	
- [ ] TableCell	
- [x] TableFooter	
- [x] TableHead	
- [ ] TablePagination	
- [x] TableRow	
- [x] TableSortLabel	
- [ ] Tabs	
- [ ] TextField	
- [x] Toolbar	
- [x] Tooltip	
- [x] Typography	
- [x] Zoom	
- [x] internal/SwitchBase	
- [ ] useMediaQuery	
- [ ] useScrollTrigger
- [ ] withMobileDialog	
- [ ] withWidth	
- [x] OverridableComponent `50 / 50` %

### CODE REVIEW

**Comment by retyui** [comment]
https://github.com/retyui/flowgen/commit/9126a613ec3b8737f44566963cfd06ca736e8ab1#diff-71aa924c8b7d4c66fa499b6c6de912ac

**Comment by retyui** [comment]
New realese: https://github.com/retyui/flowgen/commit/7c8712b59545bdda99eb7c021fad01b37365a7b6

**Comment by ochicf** [comment]
Hi @retyui!

I'm really interested in this PR, why did you close it? Did you face any blockers? How can I be of assistance?

**Comment by retyui** [comment]
@ochicf 
The `Flow.js` has too many bugs, in two months I ran into a lot of them!

I don’t see the opportunity to invest my free time in solving and solving these problems

**Pull request closed without merging**
