### PR TITLE
Update prettier definitions

### PR DESCRIPTION
**Pull request by goodmind**
- Links to documentation:
- Link to GitHub or NPM: 
- Type of contribution: new definition | addition | fix | refactor

Other notes:

### CODE REVIEW

**Comment by pascalduez** [comment]
@goodmind The tests are failing.

**Comment by goodmind** [comment]
It's only unused $ExpectError, I thought this isn't errors

**Comment by pascalduez** [comment]
The test at line 81 is not right then, since `AST` is `any` we can't actually test that.  
But you better know than me :)  
Maybe just remove it?

**Comment by goodmind** [comment]
Well, it was `Object` before

**Pull request merged**
