### PR TITLE
[cli] Allow slash comments in dependencies

### LINKED ISSUE #2537: flow-typed install should ignore the comments in package.json
**Issue:** if a package.json(as shown in below example) have comments then flow-typed install should ignore those comments.

**For example**,
**package.json:**
{
  "name": "xyz",
  "version": "0.1.0",
  ...........,
  "dependencies": {
     "//": "some comment goes here regarding the below dependency",
     "someDependency" : "0.1.0"
  }
  "scripts": {
    .......
  }
}

**Note:**
if the comments are not ignored while installing libraries then the flow-typed install fails throwing the below error:
glob error { Error: EACCES: permission denied, scandir '/lost+found'

  errno: -13,

  code: 'EACCES',

  syscall: 'scandir',

  path: '/lost+found' }

UNCAUGHT ERROR: Error: EACCES: permission denied, scandir '/lost+found'

### PR DESCRIPTION
**Pull request by Brianzchen**
Closes #2537

- Links to documentation: 
- Link to GitHub or NPM: 
- Type of contribution: new definition | addition | fix | refactor

Other notes: I preferred to create a new if block for the check so that I could document what that block specifically was for

cc @AndrewSouthpaw @rocketraman @ssvgaddam

### CODE REVIEW

**Review by GAntoine — APPROVED** [review]
Code wise this LGTM, but I'd like another pair of eyes on it.

**Comment by Brianzchen** [comment]
> Code wise this LGTM, but I'd like another pair of eyes on it.

Maybe @AndrewSouthpaw or @moroine who have familiarity with the cli codebase?

**Review by moroine — APPROVED** [review]
I don't have good knowledge on the CLI but this looks legit. However it shouldn't conflict much, the only risk is to have missing places where `name === '//'` which will only concern the new feature.

I didn't know about this comment which is great!!

H

**Comment by GAntoine** [comment]
@Brianzchen Since this shouldn't affect any existing code you're good to merge it in.

And I'm planning on doing a deploy sometime tomorrow, if things go well.

**Pull request merged**
