### PR TITLE
Improve ramda propSatisfies definition

### PR DESCRIPTION
**Pull request by moroine**
Links to documentation: https://ramdajs.com/docs/
Link to GitHub or NPM: https://github.com/ramda/ramda
Type of contribution: fix
Other notes:

### CODE REVIEW

**Comment by moroine** [comment]
@LoganBarnett could you have a look please?

**Comment by LoganBarnett** [comment]
LGTM

**Comment by AndrewSouthpaw** [comment]
There are some merge conflicts that will need to be resolved though.

**Comment by moroine** [comment]
@AndrewSouthpaw I resolved conflicts, could you merge it?

**Comment by AndrewSouthpaw** [comment]
Done! Great work @moroine !

**Pull request merged**
