### PR TITLE
[jest] add setSystemTime and fix all errors

### PR DESCRIPTION
**Pull request by Brianzchen**
The main point was to add `setSystemTime` function that was originally raised in #3913 but it fell too far behind for `./quick_run_def_tests.sh` to work properly so raising a new PR.

But I've now also cleaned up all errors in jest lib defs.

- Links to documentation: https://jestjs.io/docs/en/jest-object#jestsetsystemtimenow-number--date 
- Link to GitHub or NPM: https://www.npmjs.com/package/jest
- Type of contribution: addition

Other notes:
- Suppression codes make me wanna kill myself 💀 
- Prior to 0.134.0 (0.132, 0.133.0) errors are different so had to split the versions
- To make this PR easier to review, I've broken the commits into 3, first 2 fix the tests, and the last one adds the additional method

### CODE REVIEW

**Comment by Brianzchen** [comment]
Unrelated tests failing. tests seem to have become flaky for some other reason

**Comment by AndrewSouthpaw** [comment]
Pinging @pascalduez since I think they've often worked on reviews for jest.

**Comment by pascalduez** [comment]
Thanks a lot @Brianzchen for the hard work.

However this is impossible to review properly. 
- Files should have been git renamed instead of deleted/recreated.
- It should have only focused on the latest Jest version, 26. Until specific needs, it's not necessary to go update all previous versions IMO.
- Tests are failing in a weird way, with errors on core builtins and other libdefs... 

Anyway, we are going to trust you here :)

**Review by pascalduez — APPROVED** [review]

**Comment by pascalduez** [comment]
I wouldn't mind another reviewer approval and merge.

**Comment by Brianzchen** [comment]
Oh git rename or `git mv` would have been super helpful! I'll definitely use that next time.

**Comment by AndrewSouthpaw** [comment]
I skimmed through it, I agree with @pascalduez it's pretty tough to review. But also you've done consistently thorough work @Brianzchen and I'm fine with trusting you on this one.

Worse case scenario, something regresses and we'll tackle it as it comes up. On the whole this seems to be a lot of work to fix a lot of issues. I'll go ahead and merge.

**Review by AndrewSouthpaw — APPROVED** [review]

**Pull request merged**
