### PR TITLE
[@react-native-community/netinfo_v4.x.x] Add new definition

### PR DESCRIPTION
**Pull request by retyui**
- Links to documentation: https://github.com/react-native-community/react-native-netinfo#react-native-communitynetinfo
- Link to GitHub or NPM: https://www.npmjs.com/package/@react-native-community/netinfo
- Type of contribution: new definition

Other notes:
via: https://github.com/flow-typed/flow-typed/issues/3472

### CODE REVIEW

**Comment by MoOx** [comment]
@retyui 2 errors are related to linting/prettier

**Comment by retyui** [comment]
So...

**Comment by MoOx** [comment]
You might have to fix those error (try eslint --fix) to have CI green :) https://travis-ci.org/flow-typed/flow-typed/jobs/566005115#L339-L344

Thanks for this PR!

**Comment by retyui** [comment]
Why ?
This or add new lebdef, NOT fix for linter

**Comment by MoOx** [comment]
I am not a maintainer here, but having the "checks" all green will probably make it WAY easier to have things merged. Not ensuring that all checks are green will make it way less easier for maintainers to care about this PR because they can't merge it via GitHub UI and will have to merge it by hand while fixing the issue.

**Comment by retyui** [comment]
I do not care about linter problem!
Please,  write if you have any problems with types

**Comment by MoOx** [comment]
Don't you see that flow-typed repo have tons of PRs not merged?
You are making a good contribution and I don't understand why you don't want to fix a very tiny issue that will likely prevent to get this merged until you fix it...
If everybody is making nice contributions with tiny PRs, this will consume time to core contributors/mergers... This discussion have already cost more in terms of time that the time that would have been required to fix the initial issue. That's a shame :'(

**Comment by retyui** [comment]
If you want , please create new PR  , and fix it

**Comment by MoOx** [comment]
Oh maybe I missed the fact that this errors are not related to your addition... Sorry about that. I saw a green badge on flow-typed README so assumed incorrectly that this errors were introduced by this PR.
My bad!

**Comment by retyui** [comment]
@villesau
Ready to merge!

**Pull request merged**
