### PR TITLE
[@testing-library/react] Fix tests with suppression codes and indexer properties

### PR DESCRIPTION
**Pull request by Brianzchen**
- Links to documentation: https://testing-library.com/
- Link to GitHub or NPM: https://github.com/testing-library/react-testing-library
- Type of contribution: fix

Other notes:

### CODE REVIEW

**Comment by Brianzchen** [comment]
Using this branch and draft to figure out why the tests don't run in CI

**Comment by Brianzchen** [comment]
https://github.com/flow-typed/flow-typed/blob/master/cli/src/lib/git.js#L76
This part falls apart with this error
```
{
  stderr: "fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the working tree.\n" +
    "Use '--' to separate paths from revisions, like this:\n" +
    "'git <command> [<revision>...] -- [<file>...]'\n",
  stdout: '',
  exitCode: 128
}
```

**Comment by Brianzchen** [comment]
@pascalduez I'm pretty close to cleaning up `@testing-library/react` tests but getting one issue that comes from the 0.142.0 with indexers being more strict.

Here's the reference to the error.
https://github.com/flow-typed/flow-typed/pull/4009/checks?check_run_id=1805086782#step:5:526

I'm thinking the best thing to do is to change it from
```
CustomQueries: { [string]: (...args: Array<any>) => any, ... }
```
to
```
CustomQueries: { ... }
```

Though problem here is that it won't restrict properties passed in. Any recommendations or I'll keep digging at it?

**Review by pascalduez — APPROVED** [review]
Cool, thanks!

**Pull request merged**
