### PR TITLE
Create icons_v1.x.x

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
@GAntoine Could you help me with this failing test? I need to resolve another type `@material-ui/core`. I'm surprised because in a previous type definition that refered to "express", the module was resolved properly.

**Comment by GAntoine** [comment]
> I'm surprised because in a previous type definition that referred to "express"

I actually went ahead and changed that definition after merging, when I noticed the reference. I just didn't catch it during the review, and the flow version range was locked at `flow_v0.53.x`, instead of `flow_v0.53.x-`, which caused none of the tests to run, and therefore reported no failures.

At the moment, you can reference one library from another, though work is being done to improve that. You'll need to remove the reference and replace with custom objects, or `any`/`mixed` types.

**Comment by wcandillon** [comment]
Thanks for looking into it. Same comment as for #2311

**Comment by GAntoine** [comment]
Closing as v4 for for icons exists

**Pull request closed without merging**
