### PR TITLE
Add defs to Chai and LRUCache

### PR DESCRIPTION
**Pull request by rifflock**
- Links to documentation:
https://www.chaijs.com/api/bdd/#method_match
- Link to GitHub or NPM: 
https://www.npmjs.com/package/lru-cache/v/4.1.5
https://www.npmjs.com/package/chai

addition | fix

Other notes:
Added `prune` to LRU_Cache
Fixed chai to support `matches` alias

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Thanks for the PR! Currently your build is failing, and we'll need that to pass to merge it in. You can check out the build in Travis, or read about running libdef tests locally in CONTRIBUTING.md.

Sometimes the build was already failing for that libdef; if you can at least establish that your changes didn't introduce any new errors that would be fine too. Thanks!

**Comment by rifflock** [comment]
Looks like a bunch of warnings around unnecessary ExpectError comments that were there before. I'll remove them.

**Comment by pascalduez** [comment]
@rifflock It's most likely due to Flow > 0.75 aliasing `Object`, `Function` to `any`. So those comments are not to remove! Instead we should replace those types with stronger ones.

**Comment by rifflock** [comment]
Oh yeah, removing those comments just made it worse.

I just had to make that change in one of our internal packages when jumping from 0.66 to 0.94, let me see if I can do the same with the Chai package.

**Comment by rifflock** [comment]
Okay!
I squashed my merges because there were some useless changes in there that I reverted.
It was indeed the change in 0.88 that caused the failure. Unrelated to my changes, but better to fix it now.

**Comment by AndrewSouthpaw** [comment]
Brilliant, thanks for your work!

**Pull request merged**
