### PR TITLE
add confetti-js types

### PR DESCRIPTION
**Pull request by Brianzchen**
- Links to documentation: https://github.com/Agezao/confetti-js
- Link to GitHub or NPM: https://www.npmjs.com/package/confetti-js
- Type of contribution: new definition

Other notes:

### CODE REVIEW

**Comment by GAntoine** [comment]
Looks like the build is failing, you can see it here: https://travis-ci.org/github/flow-typed/flow-typed/jobs/701358873

**Comment by Brianzchen** [comment]
Cheers @GAntoine I notice that the PR doesn't show builds anymore is that gonna be added back or should I start looking for them in travis?

**Comment by GAntoine** [comment]
Yeah noticed that too, no idea why is happening though. In the meantime the tennis page should be public, but you may have to close/reopen PRs to rebuild.

**Comment by Brianzchen** [comment]
Looks like just an error regarding suppression_comment left which is caused by latest flow release. Anything I can do to fix my test?

**Pull request merged**
