### PR TITLE
Rewrite RxJS 6 types

### LINKED ISSUE #2272: Why is rxjs 6 flatMap overloading not working?
From the definition:
```
    flatMap<+T, U>(
      project: (value: T, index: number) => rxjs$ObservableInput<U>,
      concurrency?: number
    ): rxjs$Observable<T> => rxjs$Observable<U>;
    flatMap<+T, U, V>(
      project: (value: T, index: number) => rxjs$ObservableInput<U>,
      resultSelector: (
        outerValue: T,
        innerValue: U,
        outerIndex: number,
        innerIndex: number
      ) => V,
      concurrency?: number
    ): rxjs$Observable<T> => rxjs$Observable<V>;
```

Usage:
```
flatMap(x => of(3));
```

Error:
```
Cannot call flatMap because function [1] requires another argument.

     flow-typed/npm/rxjs_v6.x.x.js
 [1] 1020│     flatMap<+T, U, V>(
     1021│       project: (value: T, index: number) => rxjs$ObservableInput<U>,
     1022│       resultSelector: (
     1023│         outerValue: T,
     1024│         innerValue: U,
     1025│         outerIndex: number,
     1026│         innerIndex: number
     1027│       ) => V,
     1028│       concurrency?: number
     1029│     ): rxjs$Observable<T> => rxjs$Observable<V>;
```

### LINKED ISSUE #2285: RXJS 6 Missing named imports to `rxjs`
It seems that there are some named imports that are missing from the namespace `rxjs`, mainly:

- `of`
- `from`
- `pipe`
- `empty`

And maybe some more (the creation methods), but those are the ones I caught.
The definitions for `rxjs@6` only take into account this creation methods under the following path or namespace: `rxjs/observable/{observableCreator -> of, from, ...}`

Any help would be welcome! 👍 

Thanks!

### LINKED ISSUE #2356: RxJS v6 pipe with arity > 5
Disclaimer: I'm very new to Flow.

I to create a PR for this myself but couldn't seem to add an extra typing for `pipe` with an arity of 6.

After line 83 I added:

```
pipe<A, B, C, D, E, F>(
    op1: rxjs$OperatorFunction<T, A>,
    op2: rxjs$OperatorFunction<A, B>,
    op3: rxjs$OperatorFunction<B, C>,
    op4: rxjs$OperatorFunction<C, D>,
    op5: rxjs$OperatorFunction<D, E>,
    op6: rxjs$OperatorFunctionLast<E, F>
  ): F;
```

But this didn't seem to get picked up by the flow server at all... 🤔 

Does anyone want to help guide me to make a PR for this?

### LINKED ISSUE #2384: update flow definitions for Rxjs version 6.2.0
The current flow definitions are outdated and gives error If the new package syntax as mentioned in " https://rxjs-dev.firebaseapp.com/guide/v6/migration " is followed.

### LINKED ISSUE #2617: RxJS 6 type Subject does not extend Observable
In the [type definition of `Subject`](https://github.com/flow-typed/flow-typed/blob/2d80ca911ce40cfe448dfe102f3d55cf8446dfd5/definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/rxjs_v6.x.x.js#L1553), `Observable` is simply mixed in rather than extending `Observable` [as is actually the case](https://github.com/ReactiveX/rxjs/blob/master/src/internal/Subject.ts#L22). This leads to type errors whenever using a subject as an argument where an `Observable` is expected.

I came across this when using `combineLatest` and got the following error with Flow  0.67.1:

```
Cannot call combineLatest with mySubject$ bound to _ because rxjs$Subject [1] is
incompatible with undefined [2].

     src/components/search.js
 [1]  193│   mySubject$: Subject<SomeType>;
         :
      220│     // ...
      221│     const newObservable = stateObservable.pipe(
      222│       switchMap((state: State) => (
      223│         combineLatest(of(state.name), mySubject$)
      224│       )),
      225│       map(([name, instanceOfSomeType]: [string, SomeType]) => (
      226│         // ...

     flow-typed/npm/rxjs_v6.x.x.js
 [2] 1865│     combineLatest<+T, A>(a: rxjs$Observable<A>, _: void): rxjs$Observable<T> => rxjs$Observable<[T, A]>;
```

When I tried to change the definition to extend Observable (`declare class rxjs$Subject<T> extends rxjs$Observable<T> mixins rxjs$Observer<T>`, I got:

```
Cannot extend super of rxjs$Subject [1] with rxjs$Subject because:
 • function type [2] requires another argument from function type [3] in property create.
 • rxjs$Observer [4] is incompatible with function type [5] in the first argument of property
   create.

 [3]   40│   static create(
 [5]   41│     subscribe: (
       42│       observer: rxjs$Observer<T>
       43│     ) => rxjs$ISubscription | Function | void
       44│   ): rxjs$Observable<T>;
         :
     1550│   call(subscriber: rxjs$Subscriber<R>, source: any): rxjs$TeardownLogic;
     1551│ }
     1552│
 [1] 1553│ declare class rxjs$Subject<T> extends rxjs$Observable<T> mixins rxjs$Observer<T> {
 [2] 1554│   static create<T>(
 [4] 1555│     destination: rxjs$Observer<T>,
     1556│     source: rxjs$Observable<T>
     1557│   ): rxjs$AnonymousSubject<T>;
     1558│
     1559│   asObservable(): rxjs$Observable<T>;
     1560│   observers: Array<rxjs$Observer<T>>;
     1561│   unsubscribe(): void;
     1562│
     1563│   // For use in subclasses only:
     1564│   _next(value: T): void;
     1565│ }
     1566│
     1567│ declare class rxjs$AnonymousSubject<T> extends rxjs$Subject<T> {
     1568│   source: ?rxjs$Observable<T>;
```

Any thoughts on how to resolve this conflict and make the definition more correct?

### PR DESCRIPTION
**Pull request by lgeiger**
This is  a complete rewrite of the RxJS 6.3.3 flow typings. The typings were largely generated from the original typescript definitions using [`dts-bundle`](https://github.com/TypeStrong/dts-bundle) and [`flowgen`](https://github.com/joarwilk/flowgen/).
In addition, the [typescript definition test are used to validate the definitions](https://github.com/ReactiveX/rxjs/tree/master/spec-dtslint).

Also checkout https://github.com/lgeiger/rxjs-flow for the code used during the development of the typings. These typings are currently used in https://github.com/nteract/nteract/pull/3399 but it would be great to get more feedback from other users.

Closes #2617
Closes #2384
Closes #2356
Closes #2285
Closes #2272

Closes #2637
Closes #2616
Closes #2604

### CODE REVIEW

**Comment by lgeiger** [comment]
I'm really sorry for the huge diff. I still hope someone dares to check it out 😇

**Comment by lgeiger** [comment]
Any ideas why CI fails:
```
Unexpected file: rxjs_v6.x.x.js. This directory can only contain test files or a libdef file named `rxjs_v6.x.x.js`.
```

**Comment by GAntoine** [comment]
@lgeiger One of your files `definitions/npm/rxjs_v6.x.x/flow_v0.72.x-/test_zip.ts` ends in `.ts`, it might be tripping it up.

**Comment by rgbkrk** [comment]
How's this now @GAntoine?

**Comment by lgeiger** [comment]
Once this is merged. I'm happy to also upstream our [`redux-observable@1.0.0` typings](https://github.com/nteract/nteract/blob/master/types/redux-observable.js).

**Comment by rgbkrk** [comment]
If it helps -- @jayphelps, one of the leads on RxJS, also helped review these changes along with Lukas in a pairing session to get this all set with @nteract. Same goes for the redux-observable typings (which Lukas can introduce in a new PR).

**Comment by GAntoine** [comment]
Indeed that does help! In that case I'm happy to merge this in. Specs are passing and the formats look good. Great work @lgeiger and others!

**Pull request merged**
