### PR TITLE
Remove Supertype from styled-components v4+

### PR DESCRIPTION
**Pull request by tobilen**
- Links to documentation: https://flow.org/en/docs/types/utilities/#toc-supertype
- Type of contribution: fix

Other notes:
Subtype and supertype are deprecated. In this case, `$Shape` is an easy drop-in replacement.

### CODE REVIEW

**Comment by retyui** [comment]
it's a bad idea to replace to `$Shape`

**Comment by tobilen** [comment]
well, it is my understanding that `supertype` never really worked as intended and was - in practice - equivalent to an `any` type. so i'd disagree with replacing it with `shape` being a bad idea. could you elaborate why you think that?

what i do agree with is that the typing here is too loosecould be stricter. The component being returned should be one that expects the hocs props minus the props only relating to the hoc itself. I'll try to see if i can fit that into  a flowtype within the next few days

**Comment by psychobolt** [comment]
Related to #2991

**Comment by tobilen** [comment]
im still planning on doing this, sorry for not having gotten around to it yet. hopefully i'll get some time for it this week

**Comment by tobilen** [comment]
once again i am confused by the fact that tests for definitions i did not touch are suddenly failing. the v4 stuff looks good to me though

**Comment by AndrewSouthpaw** [comment]
> this will be irrelevant if #3321 gets merged.

If which one gets merged? You were referring to this PR. :-)

**Comment by tobilen** [comment]
well, technically i am still correct then! 😆 
i meant this one though: https://github.com/flow-typed/flow-typed/pull/3228

**Comment by AndrewSouthpaw** [comment]
Considering that'll create a big merge conflict with the other one, and the other one does more than this PR, I'd favor driving effort toward completing that WIP. 

Any objections?

**Comment by tobilen** [comment]
nope, let's do it 👍

**Pull request closed without merging**
