### PR TITLE
add ramda 0.27.x definitions

### LINKED ISSUE #3729: [ramda_v0.27.x] Needs to be added.
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When doing a `flow-typed install ramda@0.27.0`, it installs the `0.x.x` version. It's arguably more incorrect than `0.26.x`. Though some deprecated functions have been removed - so even `0.26.x` is not correct. It's just _less_ incorrect.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `flow-typed install ramda@0.27.x`
2. Write this code: ``` js
import { contains } from 'ramda'

contains(1, [1, 2, 3])
```
3. Run `flow status`, and see it pass (incorrectly).
4. Run the code you just wrote, and watch it break (to verify step 3).

**What is the expected behavior?**
Flow should catch non-existent functions in the latest Ramda.

**If this is a feature request, what is motivation or use case for changing the behavior?**
-
**Local Environment Information**
If this issue is specific to the CLI, provide the results of running `npx envinfo` from the command line in a GitHub gist.
-

### PR DESCRIPTION
**Pull request by LoganBarnett**
Fixes #3729.
- Links to documentation: https://github.com/ramda/ramda/pull/2835 (never made it to official release notes)
- Link to GitHub or NPM: https://ramdajs.com/ https://github.com/ramda/ramda
- Type of contribution: new definition

Other notes:

These definitions are a copy of `0.26.x` but with removed functions... removed. Some corrections were copied back to `0.26.x` - namely tests using `Object`.

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Looks like CI is pretty angry though... 
image

**Comment by moroine** [comment]
@LoganBarnett could you base your PR on https://github.com/flow-typed/flow-typed/pull/3733 ? Otherwise I can add v0.27 def in my PR, I think it would be easier to manage

**Comment by LoganBarnett** [comment]
@moroine that sounds fine by me. I need to fix some linter issues I'd missed anyways :)

**Comment by LoganBarnett** [comment]
@AndrewSouthpaw The CI is happy again. I rebased this work off of @moroine's work (already merged), so we should be good to go if there are no other concerns :)

**Comment by AndrewSouthpaw** [comment]
Sorry for the delay, merged!

**Pull request merged**
