### PR TITLE
Update react-jss_v7.x.x to flow > v0.52.x

### PR DESCRIPTION
**Pull request by clementprevot**

### CODE REVIEW

**Comment by clementprevot** [comment]
@AndrewSouthpaw I have to admit that I have no idea how to fix this build. I don't see any error in the Travis log, except the message `Flow versions not disjoint` at the bottom, but I have no idea what it means.

Would you mind helping me a bit here?

**Comment by GAntoine** [comment]
@clementprevot Change `flow_v0.52.x-` to `flow_v0.53.x-`, you're getting a `Flow version disjoint` error in the logs.

**Comment by clementprevot** [comment]
Thanks @GAntoine for your help, I will do that !

**Comment by dakota** [comment]
What is required to get this merged?

**Pull request closed without merging**
