### PR TITLE
Join `lodash` and `lodash-es` libdefs

### PR DESCRIPTION
**Pull request by antongolub**
It seems to be difficult to support several libdebs in future. `lodash-es` is a custom build with exactly the same contracts. But `get` method in `lodash`:
```javascript
get(
      object?: ?Object | ?$ReadOnlyArray<any> | void | null,
      path?: ?$ReadOnlyArray<string | number> | string | number,
      defaultValue?: any
    ): any;
```
and `lodash-es` are different:
```javascript
  declare export function get(
    object?: ?Object | ?$ReadOnlyArray<any> | void | null,
    path?: ?$ReadOnlyArray<string> | string,
    defaultValue?: any
  ): any;
```

Let's reuse `lodash` export:
```javascript
declare module "lodash-es" {
  declare module.exports: $Exports<"lodash">;
}
```
@tadaskay, @AndrewSouthpaw what do you think about?

#2444 #2436

### CODE REVIEW

**Comment by tadaskay** [comment]
Looks like the way to go. But will flowtyped pull definitions properly when it is defined in such a way (provided project has `lodash-es` dependency but not `lodash`)?

**Comment by antongolub** [comment]
@tadaskay I'm afraid will not.
@GAntoine, @AndrewSouthpaw is it possible to define [lodash-modularized packs](https://www.npmjs.com/search?q=keywords:lodash-modularized) and avoid copy-paste?

**Comment by AndrewSouthpaw** [comment]
Not sure about the modularized packs, but I think it wouldn't be the right way to go, because most people (based on no evidence whatsoever) use the general lodash package rather than the modularized ones. 

I don't think symlinking it would do what we wanted either...

I'm at a loss for how to avoid copy-pasting. @GAntoine any thoughts?

**Comment by GAntoine** [comment]
AFAIK copy-pasting is the only solution at the moment, and I don't see an easy way to avoid doing it.

> Also I don't think we should entirely delete lodash-es because there are probably people who currently depend on it, and it will unfairly break them.

Agreed.

> It should be possible to add something to a script somewhere that auto copies the files for us, but I don't have immediate thoughts about where that script would live or be executed.

We could write a script that runs on master builds (on travis) and copies the files over, kinda like what we have/are working on in the experimental branch. Though I'm just throwing out ideas.

**Comment by antongolub** [comment]
Ok. Let's do some practical steps.
1) Fix `lodash-es.get` for now: #2495 
2) Add an issue about modularized packs: #2488
3) Close this PR.

**Pull request closed without merging**
