### PR TITLE
[@testing-library/react_v11.x.x] Update definitions

### PR DESCRIPTION
**Pull request by pascalduez**
- Links to documentation: 
https://github.com/testing-library/react-testing-library/releases  
https://github.com/testing-library/dom-testing-library/releases  
- Type of contribution: addition 

Other notes:
Just trying to bring the definition a bit more up to date...

### CODE REVIEW

**Review by AndrewSouthpaw — APPROVED** [review]
LGTM, thanks @pascalduez !

**Comment by AndrewSouthpaw** [comment]
Can you comment on whether the build for this library had already been failing, or are these new build failures?

**Comment by pascalduez** [comment]
> Can you comment on whether the build for this library had already been failing, or are these new build failures?

Hey Andrew,

tests are failing for older versions than the current one (11.x). Just missing error codes to suppression comments. 
It's a bit tedious to add, so I would rather try to do it later in another MR. 
Unless someone knows a trick to add them?

**Comment by AndrewSouthpaw** [comment]
That makes sense! Merging, sorry for the slow turnaround. 😄

**Pull request merged**
