### PR TITLE
[enzyme_v3.x.x] Fix instance error

### LINKED ISSUE #925: Enzyme: Wrapper#instance() returns React$Component instead of the original component class
[`Wrapper#instance()`](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/enzyme_v2.3.x/flow_v0.28.x-/enzyme_v2.3.x.js#L50) has a return type of `React$Component<any, any, any>`. That is true, but not specific enough and if forcing me to add `$FlowFixMe` almost every time I use it.

Consider this class:

```js
class Map extend React.Component {
  zoom (zoomLevel: number): void {
    // ...
  }

  render () {
    //...
  }
}
```

And the test for `Map#zoom`:

```js
describe('#zoom', () => {
  it('zooms the map', () => {
    const tree = shallow(<Map />)
    tree.instance().zoom(16) // Flow error: property `zoom` Property not found in React$Component
  })
})
```

I think that error can be fixed using generics. If `Wrapper` knows that it is *wrapping* a type `T`, then it would be possible to do something like:

```js
declare class Wrapper<T> {
  instance(): T;
}
```

Furthermore, I think we can set a type of `React$Component<any, any, any>` to the generic `T` like so:

```js
declare class Wrapper<T: React$Component<any, any, any>> {
  instance(): T;
}
```

I would be very happy to send a PR to fix this, but I need guidance. Basically, I need to know if I'm on the right direction regarding this.

### PR DESCRIPTION
**Pull request by HsuTing**
- Links to documentation: https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/instance.md
- Link to GitHub or NPM: https://github.com/airbnb/enzyme
- Type of contribution: fix

Other notes:
Fix #925

### CODE REVIEW

**Comment by wchargin** [comment]
This PR makes it illegal to pass a `React$Node` to `render()`, yet we’ve
been doing so until now and haven’t seen any runtime type errors. Is
this change intentional, or a side-effect of the larger change?

**Comment by HsuTing** [comment]
@wangbinyq 
I think it's a side-effect of my pr. I change  `React$Element` from `React$Node` in `render()` to make wrapper being able to get the type and assign the type to `instance`. Is it possible for you to provide an example? Maybe I can clarify the problem with the example.

**Comment by wchargin** [comment]
Sure—consider the following module:

```javascript
// @flow

/*:: import type {Node as ReactNode} from "react"; */
const React = require("react");
const Enzyme = require("enzyme");
const Adapter = require("enzyme-adapter-react-16");

class MyComponent extends React.Component /*:: <{}> */ {
  render() {
    return React.createElement("div", {}, "Hello from MyComponent!");
  }
}

function makeNode1() {
  return React.createElement(MyComponent);
}

function makeNode2() {
  return React.createElement("div", {}, "Hello from a simple <span>!");
}

function makeNode(which /*: boolean */) /*: ReactNode */ {
  return which ? makeNode1() : makeNode2();
}

function test() {
  Enzyme.configure({adapter: new Adapter()});
  for (const which of [false, true]) {
    console.log(Enzyme.render(makeNode(which)).html());
  }
  console.log("OK");
}

test();
```

Running `node test.js` completes successfully:

```
$ node test.js 
Hello from a simple &lt;span&gt;!
Hello from MyComponent!
OK
```

But running `yarn flow check` gives the following errors:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ test.js:29:31

Cannot call Enzyme.render with makeNode(...) bound to node because:
 • inexact $Iterable [1] is incompatible with exact React.Element [2].
 • inexact React.Portal [1] is incompatible with exact React.Element [2].
 • inexact boolean [1] is incompatible with exact React.Element [2].
 • inexact null [1] is incompatible with exact React.Element [2].
 • inexact number [1] is incompatible with exact React.Element [2].
 • inexact string [1] is incompatible with exact React.Element [2].

     test.js
 [1]  22│ function makeNode(which /*: boolean */) /*: ReactNode */ {
      23│   return which ? makeNode1() : makeNode2();
      24│ }
      25│
      26│ function test() {
      27│   Enzyme.configure({adapter: new Adapter()});
      28│   for (const which of [false, true]) {
      29│     console.log(Enzyme.render(makeNode(which)).html());
      30│   }
      31│   console.log("OK");
      32│ }

     flow-typed/npm/enzyme_v3.x.x.js
 [2] 125│     node: React$Element<T>,

Found 6 errors
```

<details>
<summary>package.json contents</summary>

```json
{
  "name": "tmp.KjpKoG7s4R",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "flow-bin": "^0.105.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  }
}
```

</details>

Using `React.Element<any>` instead of `ReactNode` fixes the error, but
using `any` generally loses type information, so I’m a bit nervous about
making that change. Is that the right thing to do? Is it safe?

Our [real-world example][1] is pretty similar to this.

[1]: https://github.com/sourcecred/sourcecred/blob/acdcbc29ede149116cf61a04c3ecb2a7f4196ab1/src/plugins/github/render.js#L82-L93

**Comment by wchargin** [comment]
As just a partial fix for our use case (selfishly), it looks like the
change to `render` specifically could be averted without inconveniencing
others, because `render` returns a `CheerioWrapper`, not a `Foo<T>` for
any `Foo`, so the generics aren’t actually buying you anything here.

Opened #3522.

**Pull request merged**
