### PR TITLE
fix(react-apollo): add onSubscriptionData prop to Subscription (test failures are unrelated)

### PR DESCRIPTION
**Pull request by jedwards1211**
and make children optional
https://github.com/apollographql/react-apollo/blob/master/src/Subscriptions.tsx#L31

### CODE REVIEW

**Comment by jedwards1211** [comment]
```
 FAIL  src/lib/__tests__/libDefs-test.js
  ● Test suite failed to run
    TypeError: Cannot set property 'gracefulify' of undefined
      1 | // @flow
      2 | 
    > 3 | import fsExtra from 'fs-extra';
        | ^
      4 | 
      5 | import mkdirpCb from 'mkdirp';
      6 | 
```

**Comment by AndrewSouthpaw** [comment]
Looks like you checked in a yarn.lock, maybe that's part of the issue?

**Comment by jedwards1211** [comment]
Maybe, in any case that was a mistake :)

**Comment by jedwards1211** [comment]
Okay, I removed the changes to `yarn.lock`

**Pull request merged**
