### PR TITLE
upgrade current libdefs to use explicit inexact object syntax

### PR DESCRIPTION
**Pull request by pzp1997**
- Links to documentation: N/A (all current libdefs)
- Link to GitHub or NPM: N/A (all current libdefs)
- Type of contribution: refactor

Other notes:

### CODE REVIEW

**Comment by pzp1997** [comment]
This is the script I ran to generate this PR.

```
const path = require("path");
const fs = require("fs-extra");
const semver = require("semver");
const upgrade = require("flow-upgrade/dist/upgrade");

const TARGET_VERSION = "0.84.x";
const JUST_BELOW_TARGET_VERSION = "0.83.x";


// PROMISE UTILITIES

function logAndIgnoreError(...err) {
  console.error("Error", ...err);
  return Promise.resolve();
}

function passStateThrough(toPromise) {
  return (state) => toPromise(state).then(() => Promise.resolve(state));
}

function logWithinPromise(message) {
  return ((state) => {
    console.log(typeof message === "string" ? message : message(state));
    return Promise.resolve(state);
  });
}

// FS UTILITIES

function safeReaddir(directoryPath) {
  return fs.stat(directoryPath)
    .then((stat) => {
      return stat.isDirectory()
        ? Promise.resolve(directoryPath)
        : Promise.reject("not a directory");
    })
    .then(fs.readdir);
}

function readdirAlwaysResolve(directoryPath) {
  return safeReaddir(directoryPath).catch((err) => {
    console.error(`Error reading from ${directoryPath}`, err);
    return Promise.resolve([]);
  });
}

function prefixDirectories(pathPrefix, dirs) {
  return dirs.map((dir) => path.join(pathPrefix, dir));
}

// PREPARE DIRECTORIES AND RUN flow-upgrade

function enumerateLibraries(libdefPath) {
  console.log(`Enumerating libraries in ${libdefPath}`);

  return readdirAlwaysResolve(libdefPath)
    .then((dirs) => {
      const atDirectories = dirs.filter((dir) => dir.startsWith("@"));
      const nonAtDirectories = dirs.filter((dir) => !dir.startsWith("@"));
      const nonAtPaths = prefixDirectories(libdefPath, nonAtDirectories);

      return Promise.all(
        atDirectories.map((dir) =>
          readdirAlwaysResolve(path.join(libdefPath, dir))
            .then((subdirs) =>
              Promise.resolve(
                prefixDirectories(path.join(libdefPath, dir), subdirs)
              )
            )
        )
      ).then((arrayOfArrayOfPaths) =>
        Promise.resolve(
          [].concat(...arrayOfArrayOfPaths, nonAtPaths)
        )
      );
  });
}

function matchCurrentFlowVersion(flowVersion) {
  return flowVersion.match(/^flow_v((?:\d+|x)(?:\.(?:\d+|x)){0,2})-$/);
}

function findCurrentVersion(flowVersions, libraryPath) {
  const currentFlowVersion = flowVersions.find(matchCurrentFlowVersion);
  if (currentFlowVersion != null) {
    console.log(`${libraryPath}: using ${currentFlowVersion}`);

    const lowerSemver = matchCurrentFlowVersion(currentFlowVersion)[1];
    if (semver.gtr(semver.minVersion(TARGET_VERSION), lowerSemver)) {
      return Promise.resolve({
        libraryPath: libraryPath,
        original: currentFlowVersion,
        oldCopy: `${currentFlowVersion}v${JUST_BELOW_TARGET_VERSION}`,
        newCopy: `flow_v${TARGET_VERSION}-`,
        oldVersion: lowerSemver
      });
    } else {
      return Promise.resolve({
        libraryPath: libraryPath,
        original: currentFlowVersion,
        oldCopy: null,
        newCopy: currentFlowVersion,
        oldVersion: JUST_BELOW_TARGET_VERSION
      });
    }
  } else if (flowVersions.includes("flow_all")) {
    console.log(`${libraryPath}: using flow_all`);

    return Promise.resolve({
      libraryPath: libraryPath,
      original: "flow_all",
      oldCopy: `flow_v0.0.x-v${JUST_BELOW_TARGET_VERSION}`,
      newCopy: `flow_v${TARGET_VERSION}-`,
      oldVersion: "0.0.x"
    });
  } else {
    return Promise.reject("no current version");
  }
}

function copyOldVersion({ original, oldCopy, libraryPath }) {
  if (oldCopy != null) {
    console.log(`${libraryPath}: copying ${original} to ${oldCopy}`);
    return fs.copy(
      path.join(libraryPath, original),
      path.join(libraryPath, oldCopy)
    );
  } else {
    console.log(`${libraryPath}: skipping copy`);
    return Promise.resolve();
  }
}

function renameToNewVersion({ original, newCopy, libraryPath }) {
  if (original !== newCopy) {
    console.log(`${libraryPath}: renamed ${original} to ${newCopy}`);
    return fs.rename(
      path.join(libraryPath, original),
      path.join(libraryPath, newCopy)
    );
  } else {
    console.log(`${libraryPath}: skipping rename`);
    return Promise.resolve();
  }
}

function applyUpgrades(queue) {
  queue = queue.filter((task) => task != null);

  console.log(`Applying ${queue.length} upgrades`);

  return Promise.all(
    queue.map(({ libraryPath, oldVersion, newCopy }) =>
      upgrade(
        path.join(libraryPath, newCopy),
        semver.minVersion(oldVersion),
        semver.minVersion(TARGET_VERSION),
        { all: true }
      ).then(
        logWithinPromise(`${libraryPath}: upgrade complete`)
      ).catch((err) =>
        logAndIgnoreError(`${libraryPath}: problem running flow-upgrade`, err)
      )
    )
  ).then(logWithinPromise("All upgrades complete!"));
}

(function main() {
  if (process.argv.length !== 3) {
    console.error(
      "usage: node flow-typed-upgrade/index.js <path to flow-typed>"
    );
    process.exit(1);
  }

  const libdefPath = path.join(process.argv[2], "definitions");

  Promise.all([
    enumerateLibraries(path.join(libdefPath, "npm")),
    enumerateLibraries(path.join(libdefPath, "browser"))
  ])
    .then((arrayOfArrayOfPaths) =>
      Promise.resolve([].concat(...arrayOfArrayOfPaths))
    )
    .then((libraryPaths) =>
      Promise.all(
        libraryPaths.map((libraryPath) =>
          safeReaddir(libraryPath)
            .then((flowVersions) => findCurrentVersion(flowVersions, libraryPath))
            .then(passStateThrough(copyOldVersion))
            .then(passStateThrough(renameToNewVersion))
            .catch((err) =>
              logAndIgnoreError(libraryPath, err)
            )
        )
      )
    )
    .then(applyUpgrades)
    .catch(logAndIgnoreError);
}());
```

**Comment by pascalduez** [comment]
Thanks for taking the time to work on this. 
Could you provide a bit more insight/infos/explanations etc. about the changes?

The main problem I see is this is impossible to review. Also the CI is not able to test it properly, so it looks risky to merge as is.

**Comment by AndrewSouthpaw** [comment]
Also, can you run tests locally and let us know what was the result? It times out on Travis because it affects all libdefs.

**Comment by pzp1997** [comment]
@pascalduez This PR is part of the [plan to switch to exact objects by default](https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf). As an intermediate step, we need to make all objects explicitly exact/inexact. As of v0.101, I have added a lint called `implicit-inexact-object` that will warn against uses of implicit inexact object syntax. Since many people depend on flow-typed libdefs, we want to make sure they are updated to avoid triggering this lint. If you think it would make it easier to review / run the CI on, I could break up this PR into a few smaller ones. I am currently updating about 700 libdefs, so let me know how big to make each chunk.

@AndrewSouthpaw Sure, could you give me the command I should run? I have been using `./build_and_test_cli.sh` and `./quick_run_def_tests.sh` but it looks like the Travis tests are more comprehensive.

**Comment by pzp1997** [comment]
I also had to make some changes to the pre-commit hook because it was transitively depending on an old version of @babel/parser that does not support explicit inexact object syntax, i.e. it was treating stuff like `{...}` and `{foo: number, ...}` as parse errors. For now, I forked babel-eslint, bumped the version of @babel/parser it depends on to 7.4.5 (the latest on NPM), and set definitions/package.json to use my fork (https://github.com/babel/babel-eslint/compare/greenkeeper/babel-eslint-10.0.1...pzp1997:greenkeeper/babel-eslint-10.0.1). Using the fork resolved the parse errors on `...` but revealed 20 other errors unrelated to this PR that were perhaps introduced before the pre-commit hook was created (most of them are caused by redeclaring identifiers in test files). Do you think it is important for me to fix these so that the pre-commit hook passes or is using `git commit --no-verify` fine given that the errors are unrelated?

```
flow-typed/definitions/npm/styled-components_v4.x.x/flow_v0.75.x-v0.83.x/test_styled-components_v4.x.x.js
  56:11  error  Parsing error: Identifier 'derp3' has already been declared

  54 | 
  55 |     // $ExpectError
> 56 |     const derp3 = styled({})``
     |           ^
  57 | 
  58 |     // $ExpectError
  59 |     const derp3 = styled(1)``

flow-typed/definitions/npm/styled-components_v4.x.x/flow_v0.75.x-v0.83.x/test_styled-components-native.js
  21:7  error  Parsing error: Identifier 'derp3' has already been declared

  19 | 
  20 | // $ExpectError
> 21 | const derp3 = styled({})``
     |       ^
  22 | 
  23 | // $ExpectError
  24 | const derp3 = styled(1)``

flow-typed/definitions/npm/socket.io_v1.x.x/flow_v0.47.x-v0.83.x/test_socket.io_v1.x.x.js
  27:5  error  Parsing error: Identifier 'path' has already been declared

  25 | 
  26 | // $ExpectError
> 27 | let path: boolean = io.path();
     |     ^
  28 | 
  29 | let adapter = io.adapter();
  30 | io.adapter('adapter')

flow-typed/definitions/npm/redux_v4.x.x/flow_v0.89.x-/test_createStore.js
  35:7  error  Parsing error: Identifier 's' has already been declared

  33 | const s: State = store2.getState()
  34 | // $ExpectError
> 35 | const s: number = store2.getState() // wrong return type
     |       ^
  36 | 
  37 | store2.dispatch({ type: 'A' })
  38 | // $ExpectError

flow-typed/definitions/npm/redux_v3.x.x/flow_v0.89.x-/test_createStore.js
  35:7  error  Parsing error: Identifier 's' has already been declared

  33 | const s: State = store2.getState();
  34 | // $ExpectError
> 35 | const s: number = store2.getState(); // wrong return type
     |       ^
  36 | 
  37 | store2.dispatch({ type: 'A' });
  38 | // $ExpectError

flow-typed/definitions/npm/redux-saga_v0.16.x/flow_v0.56.0-v0.83.x/redux-saga_v0.16.x.js
  4:3  error  Parsing error: Imports within a `declare module` body must always be `import type` or `import typeof`

  2 | 
  3 | declare module "redux-saga" {
> 4 |   import typeof * as _effects from "redux-saga/effects";
    |   ^
  5 |   declare export var effects: _effects;
  6 | 
  7 |   declare export interface Channel {

flow-typed/definitions/npm/react-redux_v5.x.x/flow_v0.89.x-/test_connect.js
  692:10  error  Parsing error: Identifier 'doesNotRequireDefinedComponentToTypeCheck2case' has already been declared

  690 | }
  691 | 
> 692 | function doesNotRequireDefinedComponentToTypeCheck2case() {
      |          ^
  693 |   type Props = {
  694 |     stringProp: string,
  695 |     numProp: number,

flow-typed/definitions/npm/react-loadable_v5.x.x/flow_v0.56.0-v0.83.x/test_react-loadable_v5.x.x.js
  132:11  error  Parsing error: Identifier 'noWay' has already been declared

  130 | 
  131 |     // $ExpectError
> 132 |     const noWay = <Loaded2 a={1} />;
      |           ^
  133 | 
  134 |     <Loaded2 a="foo"/>
  135 |   });

flow-typed/definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-v0.83.x/test_react-apollo_v2.x.x.js
  477:17  error  Parsing error: Identifier 's' has already been declared

  475 |           // $ExpectError Cannot get `data.res` because property `res` is missing in object type
  476 |           const s: string = data.res;
> 477 |           const s: ?string = data.res;
      |                 ^
  478 |           return <div />;
  479 |         }}
  480 |       </Subscription>

flow-typed/definitions/npm/ramda_v0.x.x/flow_v0.82.x-v0.83.x/ramda_v0.x.x.js
  1920:22  error  Parsing error: Unexpected token, expected "("

  1918 |     (<A, B, C>(fn1: (b: B) => C, fn2: (a: A) => B, x: A) => C);
  1919 | 
> 1920 |   declare function of<T>(x: T): Array<T>;
       |                      ^
  1921 | 
  1922 |   declare function once<A, B, T: (...args: Array<A>) => B>(fn: T): T;
  1923 | 

flow-typed/definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.83.x/test_ramda_v0.26.x_list.js
  220:17  error  Parsing error: Identifier 'xOfXs' has already been declared

  218 |           const xOfXs: ?number = _.head(arr);
  219 |           //$ExpectError
> 220 |           const xOfXs: number = _.head(arr);
      |                 ^
  221 |         }
  222 |       });
  223 |       it('should works with refinement', () => {

flow-typed/definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.83.x/ramda_v0.26.x.js
  1753:22  error  Parsing error: Unexpected token, expected "("

  1751 |     (<A, B, C>(fn1: (b: B) => C, fn2: (a: A) => B, x: A) => C);
  1752 | 
> 1753 |   declare function of<T>(x: T): Array<T>;
       |                      ^
  1754 | 
  1755 |   declare function once<A, B, T: (...args: Array<A>) => B>(fn: T): T;
  1756 | 

flow-typed/definitions/npm/metalsmith_v2.x.x/flow_v0.75.x-v0.83.x/test_metalsmith.js
  16:7  error  Parsing error: Identifier 'file' has already been declared

  14 | 
  15 | // $ExpectError
> 16 | const file: File = {
     |       ^
  17 |   mode: '0644',
  18 | };
  19 | 

flow-typed/definitions/npm/klasa_v0.3.x/flow_v0.39.0-v0.83.x/klasa_v0.3.x.js
  324:20  error  Parsing error: Export 'KlasaClient' is not defined

  322 |   }
  323 | 
> 324 |   declare export { KlasaClient as Client };
      |                    ^
  325 | 
  326 |   declare export class ReactionHandler {
  327 |     constructor(

flow-typed/definitions/npm/io-ts_v1.3.x/flow_v0.72.x-v0.83.x/io-ts_v1.3.x.js
  734:20  error  Parsing error: Export 'nullType' is not defined

  732 |   declare export type PropsOf<T: { props: any }> = $PropertyType<T,'props'>;
  733 | 
> 734 |   declare export { nullType as null, undefinedType as undefined, arrayType as Array, type as interface, voidType as void }
      |                    ^
  735 | }
  736 | 

flow-typed/definitions/npm/gl-matrix_v2.x.x/flow_v0.25.x-v0.83.x/test_gl-matrix_v2.x.x.js
  85:9  error  Parsing error: Identifier 'c1' has already been declared

  83 | 
  84 |   // $ExpectError
> 85 |   const c1: Mat4 = mat4.mul(a, b);
     |         ^
  86 | 
  87 |   // $ExpectError
  88 |   const c1: number = mat4.mul(a, b, c);

flow-typed/definitions/npm/fetch-ponyfill_v3.x.x/flow_v0.28.x-v0.83.x/test_fetch-ponyfill_v3.x.x.js
  39:7  error  Parsing error: Identifier '_fetch1' has already been declared

  37 | const _fetch1 = FetchConstructor({Promise, XMLHttpRequest}).fetch;
  38 | //$ExpectError
> 39 | const _fetch1 = FetchConstructor({Promise: () => null}).fetch;
     |       ^
  40 | 

flow-typed/definitions/npm/directory-tree_v2.x.x/flow_v0.71.x-v0.83.x/directory-tree_v2.x.x.js
  2:3  error  Parsing error: Imports within a `declare module` body must always be `import type` or `import typeof`

  1 | declare module 'directory-tree' {
> 2 |   import typeof pathType from 'path';
    |   ^
  3 | 
  4 |   declare type directoryNodeType = {|
  5 |     path: string,

flow-typed/definitions/npm/backbone_v1.x.x/flow_v0.42.x-v0.83.x/backbone_v1.x.x.js
  313:16  error  Parsing error: `_` is only allowed as a type argument to call or new

  311 |     // Utilty
  312 |     $: typeof $; // @TODO this is no correct, but it is difficult to require another definition from here.
> 313 |     _: typeof _; // @TODO this is no correct, but it is difficult to require another definition from here.
      |                ^
  314 |     version: typeof version;
  315 |     noConflict(): this;
  316 |   }

flow-typed/definitions/npm/@material-ui/icons_v4.x.x/flow_v0.69.x-v0.83.x/icons_v4.x.x.js
  46:3  error  Parsing error: Imports within a `declare module` body must always be `import type` or `import typeof`

  44 | 
  45 | declare module '@material-ui/icons/AccessAlarm' {
> 46 |   import typeof SvgIcon from '@material-ui/core/@@SvgIcon';
     |   ^
  47 |   declare export default SvgIcon;
  48 | }
  49 | declare module '@material-ui/icons/AccessAlarmOutlined' {

husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by pascalduez** [comment]
@pzp1997 Thanks for the explanations, make more sense now.  

> If you think it would make it easier to review / run the CI on, I could break up this PR into a few smaller ones. I am currently updating about 700 libdefs, so let me know how big to make each chunk.

That would probably be much hassle as well. 
However if you have a way to split into two commits, one for the file renaming/copying, and one for the changes, we could have a "real" diff to look at. Otherwise don't bother.

**Comment by goodmind** [comment]
Any updates here?

**Comment by AndrewSouthpaw** [comment]
Agreed what @pascalduez said.

For the tests travis runs, I think quick run script should do it, whatever ends up getting used in `travis.sh`. Or you could run that script.

It may be that your machine is just many times faster than travis and so you blaze through the tests. Are you at least getting similar output to the Travis logs?

**Comment by AndrewSouthpaw** [comment]
Also, great work. :)

**Comment by villesau** [comment]
I've skimmed trough some and looks good to me! I could take closer look during the weekend, run the tests locally and rebase. Maybe even merge? The sooner we get this in the better. This has so massive conflict surface that this rots in a day.

We also need some linter to prevent `{ a: number }` syntax without `...` during the transition period..

**Comment by AndrewSouthpaw** [comment]
Thanks @villesau. I'm swamped until next week and wouldn't have time to properly look through the thing.

**Comment by villesau** [comment]
I've now run some tests manually, but not the full test suite. Seems to be working well. How do we prevent inexact objects without `...`? I didn't find anything from here for example: https://github.com/gajus/eslint-plugin-flowtype

**Comment by goodmind** [comment]
@villesau there's lint in new versions

**Comment by villesau** [comment]
@pzp1997 Could you add the new lint option in test runner? In `runTests.js:294 - 311` we generate flow config for each test and probably from 0.101 onwards we should enforce the explicit inexactness.

Here is an example pull request that could be useful for you where I removed conditional flow config generation before since at that point it was legacy clutter but now it could be useful again: https://github.com/flow-typed/flow-typed/pull/2750

**Comment by AndrewSouthpaw** [comment]
I imagine @pzp1997 you have other stuff going on, but the longer this sits the more stale it gets, and I'm adding new conflicts each day by merging other PRs. :-( LMK if there's anything you need on my end. I'm okay with it being merged in as long as someone can confirm that no new regressions were introduced.

**Comment by villesau** [comment]
@AndrewSouthpaw on the other hadn it's fairly easy to run the script from scratch as well.

**Comment by goodmind** [comment]
@pzp1997 when would you be able to continue work on this?

**Comment by jbrown215** [comment]
Spoke with @pzp, I'll take this one over.

**Comment by AndrewSouthpaw** [comment]
It seeeems like this one is closed in favor of the one you just referenced? Closing for now, feel free to request otherwise.

**Pull request closed without merging**
