### PR TITLE
Add inclusive paramter to takeWhile predicate

### PR DESCRIPTION
**Pull request by tobilen**
- Links to documentation: https://www.learnrxjs.io/operators/filtering/takewhile.html
- Link to GitHub or NPM: https://github.com/ReactiveX/rxjs/pull/4115/files
- Type of contribution: fix

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Thanks for the PR! Currently your build is failing, and we'll need that to pass to merge it in. You can check out the build in Travis, or read about running libdef tests locally in CONTRIBUTING.md.

**Comment by tobilen** [comment]
yes. the thing is, they're failing even when i revert my commit. i didn't change any of the stuff thats failing. i'll take a look, but help would be appreciated

**Comment by pascalduez** [comment]
Looks like the changes introduced in Flow `0.99` regarding function statics.   
So not related to this PR.

**Comment by AndrewSouthpaw** [comment]
Thanks all.

**Pull request merged**
