### PR TITLE
[recompose_v0.26.x] Lock flow version

### PR DESCRIPTION
**Pull request by retyui**
- Links to documentation: https://github.com/acdlite/recompose/blob/master/docs/API.md
- Link to GitHub or NPM: https://github.com/acdlite/recompose
- Type of contribution: refactor

The Problem:
When you run a command:
```sh
node cli/dist/cli.js run-tests recompose
```
you will see many problems associated with some flow.js updates

### CODE REVIEW

**Comment by retyui** [comment]
what has been changed:
```diff
-definitions/npm/recompose_v0.26.x
+definitions/npm/recompose_v0.x.x

-definitions/npm/recompose_v0.x.x/flow_v0.57.x-
+definitions/npm/recompose_v0.x.x/flow_v0.57.x-v0.87.x
```

**Comment by pascalduez** [comment]
Why the `0.26.x` rename into `0.x.x`, maybe there was there was specific stuff in there that don't apply to lower than `0.26` versions? 

What about Flow versions higher than `0.87`?

**Comment by retyui** [comment]
> Why the 0.26.x rename into 0.x.x, maybe there was there was specific stuff in there that don't apply to lower than 0.26 versions?

you are right, I will cancel this change.

> What about Flow versions higher than 0.87?

nothing yet

**Comment by retyui** [comment]
[0.27.0](https://github.com/acdlite/recompose/releases/tag/0.27.0)

> Flow types are now distributed with recompose, please delete flow-typed recompose lib defs. #649

**Pull request merged**
